import { GearType, type Enchant } from './raidTemplate';

export const ESO_ENCHANTS: Enchant[] = [
  { id: 1, name: 'Glyph of Health', gearType: GearType.armor },
  { id: 2, name: 'Glyph of Magicka', gearType: GearType.armor },
  { id: 3, name: 'Glyph of Prismatic Defense', gearType: GearType.armor },
  { id: 4, name: 'Glyph of Stamina', gearType: GearType.armor },
  { id: 5, name: 'Glyph ofAbosrb Health', gearType: GearType.weapon },
  { id: 6, name: 'Glyph of Abosrb Magicka', gearType: GearType.weapon },
  { id: 7, name: 'Glyph of Abosrb Stamina', gearType: GearType.weapon },
  { id: 8, name: 'Glyph of Crushing', gearType: GearType.weapon },
  { id: 9, name: 'Glyph of Decrease Health', gearType: GearType.weapon },
  { id: 10, name: 'Glyph of Flame', gearType: GearType.weapon },
  { id: 11, name: 'Glyph of Foulness', gearType: GearType.weapon },
  { id: 12, name: 'Glyph of Frost', gearType: GearType.weapon },
  { id: 13, name: 'Glyph of Hardening', gearType: GearType.weapon },
  { id: 14, name: 'Glyph of Poison', gearType: GearType.weapon },
  { id: 15, name: 'Glyph of Prismatic Onslaught', gearType: GearType.weapon },
  { id: 16, name: 'Glyph of Shock', gearType: GearType.weapon },
  { id: 17, name: 'Glyph of Weakening', gearType: GearType.weapon },
  { id: 18, name: 'Glyph of Weapon Damage', gearType: GearType.weapon },
  { id: 19, name: 'Glyph of Bashing', gearType: GearType.jewelry },
  { id: 20, name: 'Glyph of Bracing', gearType: GearType.jewelry },
  { id: 21, name: 'Glyph of Decrease Physical Harm', gearType: GearType.jewelry },
  { id: 22, name: 'Glyph of Decrease Spell Harm', gearType: GearType.jewelry },
  { id: 23, name: 'Glyph of Disease Resist', gearType: GearType.jewelry },
  { id: 24, name: 'Glyph of Flame Resist', gearType: GearType.jewelry },
  { id: 25, name: 'Glyph of Frost Resist', gearType: GearType.jewelry },
  { id: 26, name: 'Glyph of Health Recovery', gearType: GearType.jewelry },
  { id: 27, name: 'Glyph of Increase Magical Harm', gearType: GearType.jewelry },
  { id: 28, name: 'Glyph of Increase Physical Harm', gearType: GearType.jewelry },
  { id: 29, name: 'Glyph of Magicka Recovery', gearType: GearType.jewelry },
  { id: 30, name: 'Glyph of Poison Resist', gearType: GearType.jewelry },
  { id: 31, name: 'Glyph of Potion Speed', gearType: GearType.jewelry },
  { id: 32, name: 'Glyph of Prismatic Recovery', gearType: GearType.jewelry },
  { id: 33, name: 'Glyph of Reduce Feat Cost', gearType: GearType.jewelry },
  { id: 34, name: 'Glyph of Reduce Skill Cost', gearType: GearType.jewelry },
  { id: 35, name: 'Glyph of Reduce Spell Cost', gearType: GearType.jewelry },
  { id: 36, name: 'Glyph of Shock Resist', gearType: GearType.jewelry },
  { id: 37, name: 'Glyph of Stamina Recovery', gearType: GearType.jewelry },
  { id: 38, name: 'Glyph of Bracing', gearType: GearType.jewelry },

];
