import type { Set } from './raidTemplate';

export const ESO_SETS: Set[] = [
  { id: 1, setName: "Death's Wind", effects: [] },
  { id: 2, setName: "Twilight's Embrace", effects: [] },
  { id: 3, setName: "Night's Silence", effects: [] },
  { id: 4, setName: "Whitestrake's Retribution", effects: [] },
  { id: 5, setName: "Armor of the Seducer", effects: [] },
  { id: 6, setName: "Vampire's Kiss", effects: [] },
  { id: 7, setName: "Magnus' Gift", effects: [] },
  { id: 8, setName: "Night Mother's Gaze", effects: [] },
  { id: 9, setName: "Ashen Grip", effects: [] },
  { id: 10, setName: "Oblivion's Foe", effects: [] },
  { id: 11, setName: "Spectre's Eye", effects: [] },
  { id: 12, setName: "Torug's Pact", effects: [] },
  { id: 13, setName: "Hist Bark", effects: [] },
  { id: 14, setName: "Willow's Path", effects: [] },
  { id: 15, setName: "Hunding's Rage", effects: [] },
  { id: 16, setName: "Song of Lamae", effects: [] },
  { id: 17, setName: "Alessia's Bulwark", effects: [] },
  { id: 18, setName: "Orgnum's Scales", effects: [] },
  { id: 19, setName: "Eyes of Mara", effects: [] },
  { id: 20, setName: "Kagrenac's Hope", effects: [] },
  { id: 21, setName: "Shalidor's Curse", effects: [] },
  { id: 22, setName: "Way of the Arena", effects: [] },
  { id: 23, setName: "Grand Rejuvenation", effects: [] },
  { id: 24, setName: "Puncturing Remedy", effects: [] },
  { id: 25, setName: "Titanic Cleave", effects: [] },
  { id: 26, setName: "Caustic Arrow", effects: [] },
  { id: 27, setName: "Destructive Impact", effects: [] },
  { id: 28, setName: "Twice-Born Star", effects: [] },
  { id: 29, setName: "Spawn of Mephala", effects: [] },
  { id: 30, setName: "Bloodspawn", effects: [] },
  { id: 31, setName: "Lord Warden", effects: [] },
  { id: 32, setName: "Scourge Harvester", effects: [] },
  { id: 33, setName: "Engine Guardian", effects: [] },
  { id: 34, setName: "Nightflame", effects: [] },
  { id: 35, setName: "Nerien'eth", effects: [] },
  { id: 36, setName: "Valkyn Skoria", effects: [] },
  { id: 37, setName: "Maw of the Infernal", effects: [] },
  { id: 38, setName: "Noble's Conquest", effects: [] },
  { id: 39, setName: "Redistributor", effects: [] },
  { id: 40, setName: "Armor Master", effects: [] },
  { id: 41, setName: "Molag Kena", effects: [] },
  { id: 42, setName: "Black Rose", effects: [] },
  { id: 43, setName: "Trinimac's Valor", effects: [] },
  { id: 44, setName: "Briarheart", effects: [] },
  { id: 45, setName: "Winterborn", effects: [] },
  { id: 46, setName: "Powerful Assault", effects: [] },
  { id: 47, setName: "Mark of the Pariah", effects: [] },
  { id: 48, setName: "Meritorious Service", effects: [] },
  { id: 49, setName: "Para Bellum", effects: [] },
  { id: 50, setName: "Glorious Defender", effects: [] },
  { id: 51, setName: "Elemental Succession", effects: [] },
  { id: 52, setName: "Shield Breaker", effects: [] },
  { id: 53, setName: "Permafrost", effects: [] },
  { id: 54, setName: "Phoenix", effects: [] },
  { id: 55, setName: "Hunt Leader", effects: [] },
  { id: 56, setName: "Reactive Armor", effects: [] },
  { id: 57, setName: "Endurance", effects: [] },
  { id: 58, setName: "Willpower", effects: [] },
  { id: 59, setName: "Agility", effects: [] },
  { id: 60, setName: "Law of Julianos", effects: [] },
  { id: 61, setName: "Trial by Fire", effects: [] },
  { id: 62, setName: "Morkuldin", effects: [] },
  { id: 63, setName: "Cruel Flurry", effects: [] },
  { id: 64, setName: "Rampaging Slash", effects: [] },
  { id: 65, setName: "Merciless Charge", effects: [] },
  { id: 66, setName: "Thunderous Volley", effects: [] },
  { id: 67, setName: "Crushing Wall", effects: [] },
  { id: 68, setName: "Tava's Favor", effects: [] },
  { id: 69, setName: "Clever Alchemist", effects: [] },
  { id: 70, setName: "Eternal Hunt", effects: [] },
  { id: 71, setName: "Bahraha's Curse", effects: [] },
  { id: 72, setName: "Syvarra's Scales", effects: [] },
  { id: 73, setName: "Moondancer", effects: [] },
  { id: 74, setName: "Twilight Remedy", effects: [] },
  { id: 75, setName: "Roar of Alkosh", effects: [] },
  { id: 76, setName: "Lunar Bastion", effects: [] },
  { id: 77, setName: "Marksman's Crest", effects: [] },
  { id: 78, setName: "Leki's Focus", effects: [] },
  { id: 79, setName: "Fasalla's Guile", effects: [] },
  { id: 80, setName: "Warrior's Fury", effects: [] },
  { id: 81, setName: "Vicious Death", effects: [] },
  { id: 82, setName: "Robes of Transmutation", effects: [] },
  { id: 83, setName: "Darkstride", effects: [] },
  { id: 84, setName: "Shadow Dancer's Raiment", effects: [] },
  { id: 85, setName: "Kvatch Gladiator", effects: [] },
  { id: 86, setName: "Varen's Legacy", effects: [] },
  { id: 87, setName: "Pelinal's Wrath", effects: [] },
  { id: 88, setName: "Hide of Morihaus", effects: [] },
  { id: 89, setName: "Flanking Strategist", effects: [] },
  { id: 90, setName: "Sithis' Touch", effects: [] },
  { id: 91, setName: "Galerion's Revenge", effects: [] },
  { id: 92, setName: "Vicecanon of Venom", effects: [] },
  { id: 93, setName: "Thews of the Harbinger", effects: [] },
  { id: 94, setName: "Imperial Physique", effects: [] },
  { id: 95, setName: "Precise Regeneration", effects: [] },
  { id: 96, setName: "Eternal Warrior", effects: [] },
  { id: 97, setName: "Vicious Serpent", effects: [] },
  { id: 98, setName: "Infallible Mage", effects: [] },
  { id: 99, setName: "Queen's Elegance", effects: [] },
  { id: 100, setName: "Senche's Bite", effects: [] },
  { id: 101, setName: "Velidreth", effects: [] },
  { id: 102, setName: "Mighty Chudan", effects: [] },
  { id: 103, setName: "Aspect of Mazzatun", effects: [] },
  { id: 104, setName: "Amber Plasm", effects: [] },
  { id: 105, setName: "Heem-Jas' Retribution", effects: [] },
  { id: 106, setName: "Hand of Mephala", effects: [] },
  { id: 107, setName: "Gossamer", effects: [] },
  { id: 108, setName: "Widowmaker", effects: [] },
  { id: 109, setName: "Akaviri Dragonguard", effects: [] },
  { id: 110, setName: "Silks of the Sun", effects: [] },
  { id: 111, setName: "Shadow of the Red Mountain", effects: [] },
  { id: 112, setName: "Syrabane's Grip", effects: [] },
  { id: 113, setName: "Salvation", effects: [] },
  { id: 114, setName: "Hide of the Werewolf", effects: [] },
  { id: 115, setName: "Robes of the Withered Hand", effects: [] },
  { id: 116, setName: "Storm Knight's Plate", effects: [] },
  { id: 117, setName: "Necropotence", effects: [] },
  { id: 118, setName: "Footman's Fortune", effects: [] },
  { id: 119, setName: "Healer's Habit", effects: [] },
  { id: 120, setName: "Robes of Destruction Mastery", effects: [] },
  { id: 121, setName: "Archer's Mind", effects: [] },
  { id: 122, setName: "Blessing of the Potentates", effects: [] },
  { id: 123, setName: "Deadly Strike", effects: [] },
  { id: 124, setName: "Alessian Order", effects: [] },
  { id: 125, setName: "Crest of Cyrodiil", effects: [] },
  { id: 126, setName: "Bastion of the Heartland", effects: [] },
  { id: 127, setName: "Beckoning Steel", effects: [] },
  { id: 128, setName: "The Juggernaut", effects: [] },
  { id: 129, setName: "Affliction", effects: [] },
  { id: 130, setName: "Ravager", effects: [] },
  { id: 131, setName: "Elf Bane", effects: [] },
  { id: 132, setName: "Wrath of the Imperium", effects: [] },
  { id: 133, setName: "Grace of the Ancients", effects: [] },
  { id: 134, setName: "Desert Rose", effects: [] },
  { id: 135, setName: "Curse Eater", effects: [] },
  { id: 136, setName: "Almalexia's Mercy", effects: [] },
  { id: 137, setName: "Robes of Alteration Mastery", effects: [] },
  { id: 138, setName: "The Arch-Mage", effects: [] },
  { id: 139, setName: "Light of Cyrodiil", effects: [] },
  { id: 140, setName: "Buffer of the Swift", effects: [] },
  { id: 141, setName: "Eagle Eye", effects: [] },
  { id: 142, setName: "Vengeance Leech", effects: [] },
  { id: 143, setName: "Twin Sisters", effects: [] },
  { id: 144, setName: "Shield of the Valiant", effects: [] },
  { id: 145, setName: "Shadow Walker", effects: [] },
  { id: 146, setName: "Hawk's Eye", effects: [] },
  { id: 147, setName: "The Morag Tong", effects: [] },
  { id: 148, setName: "Kyne's Kiss", effects: [] },
  { id: 149, setName: "Ward of Cyrodiil", effects: [] },
  { id: 150, setName: "Sentry", effects: [] },
  { id: 151, setName: "Armor of the Veiled Heritance", effects: [] },
  { id: 152, setName: "Swarm Mother", effects: [] },
  { id: 153, setName: "Slimecraw", effects: [] },
  { id: 154, setName: "Tremorscale", effects: [] },
  { id: 155, setName: "Pirate Skeleton", effects: [] },
  { id: 156, setName: "Shadowrend", effects: [] },
  { id: 157, setName: "Sentinel of Rkugamz", effects: [] },
  { id: 158, setName: "Chokethorn", effects: [] },
  { id: 159, setName: "Infernal Guardian", effects: [] },
  { id: 160, setName: "Ilambris", effects: [] },
  { id: 161, setName: "Iceheart", effects: [] },
  { id: 162, setName: "The Troll King", effects: [] },
  { id: 163, setName: "Grothdarr", effects: [] },
  { id: 164, setName: "Kra'gh", effects: [] },
  { id: 165, setName: "Sellistrix", effects: [] },
  { id: 166, setName: "Stormfist", effects: [] },
  { id: 167, setName: "Selene", effects: [] },
  { id: 168, setName: "Way of Fire", effects: [] },
  { id: 169, setName: "Way of Martial Knowledge", effects: [] },
  { id: 170, setName: "Way of Air", effects: [] },
  { id: 171, setName: "Armor of the Trainee", effects: [] },
  { id: 172, setName: "Bloodthorn's Touch", effects: [] },
  { id: 173, setName: "Shalk Exoskeleton", effects: [] },
  { id: 174, setName: "Wyrd Tree's Blessing", effects: [] },
  { id: 175, setName: "Night Mother's Embrace", effects: [] },
  { id: 176, setName: "Plague Doctor", effects: [] },
  { id: 177, setName: "Mother's Sorrow", effects: [] },
  { id: 178, setName: "Wilderqueen's Arch", effects: [] },
  { id: 179, setName: "Green Pact", effects: [] },
  { id: 180, setName: "Night Terror", effects: [] },
  { id: 181, setName: "Dreamer's Mantle", effects: [] },
  { id: 182, setName: "Ranger's Gait", effects: [] },
  { id: 183, setName: "Beekeeper's Gear", effects: [] },
  { id: 184, setName: "Vampire Cloak", effects: [] },
  { id: 185, setName: "Robes of the Hist", effects: [] },
  { id: 186, setName: "Swamp Raider", effects: [] },
  { id: 187, setName: "Hatchling's Shell", effects: [] },
  { id: 188, setName: "Sword-Singer", effects: [] },
  { id: 189, setName: "Order of Diagna", effects: [] },
  { id: 190, setName: "Spinner's Garments", effects: [] },
  { id: 191, setName: "Thunderbug's Carapace", effects: [] },
  { id: 192, setName: "Stendarr's Embrace", effects: [] },
  { id: 193, setName: "Fiord's Legacy", effects: [] },
  { id: 194, setName: "Vampire Lord", effects: [] },
  { id: 195, setName: "Spriggan's Thorns", effects: [] },
  { id: 196, setName: "Seventh Legion Brute", effects: [] },
  { id: 197, setName: "Skooma Smuggler", effects: [] },
  { id: 198, setName: "Soulshine", effects: [] },
  { id: 199, setName: "Ysgramor's Birthright", effects: [] },
  { id: 200, setName: "Witchman Armor", effects: [] },
  { id: 201, setName: "Draugr's Heritage", effects: [] },
  { id: 202, setName: "Prisoner's Rags", effects: [] },
  { id: 203, setName: "Stygian", effects: [] },
  { id: 204, setName: "Meridia's Blessed Armor", effects: [] },
  { id: 205, setName: "Sanctuary", effects: [] },
  { id: 206, setName: "Jailbreaker", effects: [] },
  { id: 207, setName: "Tormentor", effects: [] },
  { id: 208, setName: "Spelunker", effects: [] },
  { id: 209, setName: "Spider Cultist Cowl", effects: [] },
  { id: 210, setName: "Light Speaker", effects: [] },
  { id: 211, setName: "Undaunted Bastion", effects: [] },
  { id: 212, setName: "Combat Physician", effects: [] },
  { id: 213, setName: "Toothrow", effects: [] },
  { id: 214, setName: "Netch's Touch", effects: [] },
  { id: 215, setName: "Strength of the Automaton", effects: [] },
  { id: 216, setName: "Burning Spellweave", effects: [] },
  { id: 217, setName: "Sunderflame", effects: [] },
  { id: 218, setName: "Embershield", effects: [] },
  { id: 219, setName: "Hircine's Veneer", effects: [] },
  { id: 220, setName: "Sword Dancer", effects: [] },
  { id: 221, setName: "Treasure Hunter", effects: [] },
  { id: 222, setName: "Duneripper's Scales", effects: [] },
  { id: 223, setName: "Shroud of the Lich", effects: [] },
  { id: 224, setName: "Leviathan", effects: [] },
  { id: 225, setName: "Ebon Armory", effects: [] },
  { id: 226, setName: "Lamia's Song", effects: [] },
  { id: 227, setName: "Undaunted Infiltrator", effects: [] },
  { id: 228, setName: "Medusa", effects: [] },
  { id: 229, setName: "Magicka Furnace", effects: [] },
  { id: 230, setName: "Draugr Hulk", effects: [] },
  { id: 231, setName: "Undaunted Unweaver", effects: [] },
  { id: 232, setName: "Bone Pirate's Tatters", effects: [] },
  { id: 233, setName: "Knight-Errant's Mail", effects: [] },
  { id: 234, setName: "Prayer Shawl", effects: [] },
  { id: 235, setName: "Knightmare", effects: [] },
  { id: 236, setName: "Viper's Sting", effects: [] },
  { id: 237, setName: "Dreugh King Slayer", effects: [] },
  { id: 238, setName: "Barkskin", effects: [] },
  { id: 239, setName: "Sergeant's Mail", effects: [] },
  { id: 240, setName: "Armor of Truth", effects: [] },
  { id: 241, setName: "Crusader", effects: [] },
  { id: 242, setName: "The Ice Furnace", effects: [] },
  { id: 243, setName: "Vestments of the Warlock", effects: [] },
  { id: 244, setName: "Durok's Bane", effects: [] },
  { id: 245, setName: "Noble Duelist's Silks", effects: [] },
  { id: 246, setName: "Nikulas' Heavy Armor", effects: [] },
  { id: 247, setName: "Overwhelming Surge", effects: [] },
  { id: 248, setName: "Storm Master", effects: [] },
  { id: 249, setName: "Jolting Arms", effects: [] },
  { id: 250, setName: "The Worm's Raiment", effects: [] },
  { id: 251, setName: "Oblivion's Edge", effects: [] },
  { id: 252, setName: "Rattlecage", effects: [] },
  { id: 253, setName: "Scathing Mage", effects: [] },
  { id: 254, setName: "Sheer Venom", effects: [] },
  { id: 255, setName: "Leeching Plate", effects: [] },
  { id: 256, setName: "Spell Power Cure", effects: [] },
  { id: 257, setName: "Essence Thief", effects: [] },
  { id: 258, setName: "Brands of Imperium", effects: [] },
  { id: 259, setName: "Healing Mage", effects: [] },
  { id: 260, setName: "Quick Serpent", effects: [] },
  { id: 261, setName: "Defending Warrior", effects: [] },
  { id: 262, setName: "Destructive Mage", effects: [] },
  { id: 263, setName: "Poisonous Serpent", effects: [] },
  { id: 264, setName: "Berserking Warrior", effects: [] },
  { id: 265, setName: "Wise Mage", effects: [] },
  { id: 266, setName: "Twice-Fanged Serpent", effects: [] },
  { id: 267, setName: "Immortal Warrior", effects: [] },
  { id: 268, setName: "Assassin's Guile", effects: [] },
  { id: 269, setName: "Daedric Trickery", effects: [] },
  { id: 270, setName: "Shacklebreaker", effects: [] },
  { id: 271, setName: "Defiler", effects: [] },
  { id: 272, setName: "War Maiden", effects: [] },
  { id: 273, setName: "Warrior-Poet", effects: [] },
  { id: 274, setName: "Automated Defense", effects: [] },
  { id: 275, setName: "Inventor's Guard", effects: [] },
  { id: 276, setName: "Master Architect", effects: [] },
  { id: 277, setName: "War Machine", effects: [] },
  { id: 278, setName: "Coward's Gear", effects: [] },
  { id: 279, setName: "Knight Slayer", effects: [] },
  { id: 280, setName: "Impregnable Armor", effects: [] },
  { id: 281, setName: "Vanguard's Challenge", effects: [] },
  { id: 282, setName: "Wizard's Riposte", effects: [] },
  { id: 283, setName: "Ironblood", effects: [] },
  { id: 284, setName: "Draugr's Rest", effects: [] },
  { id: 285, setName: "Pillar of Nirn", effects: [] },
  { id: 286, setName: "Hagraven's Garden", effects: [] },
  { id: 287, setName: "Flame Blossom", effects: [] },
  { id: 288, setName: "Blooddrinker", effects: [] },
  { id: 289, setName: "Earthgore", effects: [] },
  { id: 290, setName: "Domihaus", effects: [] },
  { id: 291, setName: "Innate Axiom", effects: [] },
  { id: 292, setName: "Fortified Brass", effects: [] },
  { id: 293, setName: "Mechanical Acuity", effects: [] },
  { id: 294, setName: "Mad Tinkerer", effects: [] },
  { id: 295, setName: "Unfathomable Darkness", effects: [] },
  { id: 296, setName: "Livewire", effects: [] },
  { id: 297, setName: "Perfected Timeless Blessing", effects: [] },
  { id: 298, setName: "Perfected Chaotic Whirlwind", effects: [] },
  { id: 299, setName: "Perfected Disciplined Slash", effects: [] },
  { id: 300, setName: "Perfected Piercing Spray", effects: [] },
  { id: 301, setName: "Perfected Concentrated Force", effects: [] },
  { id: 302, setName: "Perfected Defensive Position", effects: [] },
  { id: 303, setName: "Timeless Blessing", effects: [] },
  { id: 304, setName: "Chaotic Whirlwind", effects: [] },
  { id: 305, setName: "Disciplined Slash", effects: [] },
  { id: 306, setName: "Piercing Spray", effects: [] },
  { id: 307, setName: "Concentrated Force", effects: [] },
  { id: 308, setName: "Defensive Position", effects: [] },
  { id: 309, setName: "Adept Rider", effects: [] },
  { id: 310, setName: "Sload's Semblance", effects: [] },
  { id: 311, setName: "Nocturnal's Favor", effects: [] },
  { id: 312, setName: "Wisdom of Vanus", effects: [] },
  { id: 313, setName: "Gryphon's Ferocity", effects: [] },
  { id: 314, setName: "Grace of Gloom", effects: [] },
  { id: 315, setName: "Mantle of Siroria", effects: [] },
  { id: 316, setName: "Vestment of Olorime", effects: [] },
  { id: 317, setName: "Arms of Relequen", effects: [] },
  { id: 318, setName: "Aegis of Galenwe", effects: [] },
  { id: 319, setName: "Zaan", effects: [] },
  { id: 320, setName: "Thurvokun", effects: [] },
  { id: 321, setName: "Caluurion's Legacy", effects: [] },
  { id: 322, setName: "Jorvuld's Guidance", effects: [] },
  { id: 323, setName: "Trappings of Invigoration", effects: [] },
  { id: 324, setName: "Plague Slinger", effects: [] },
  { id: 325, setName: "Ulfnor's Favor", effects: [] },
  { id: 326, setName: "Curse of Doylemish", effects: [] },
  { id: 327, setName: "Perfected Aegis of Galenwe", effects: [] },
  { id: 328, setName: "Perfected Vestment of Olorime", effects: [] },
  { id: 329, setName: "Perfected Arms of Relequen", effects: [] },
  { id: 330, setName: "Perfected Mantle of Siroria", effects: [] },
  { id: 331, setName: "Stinging Slashes", effects: [] },
  { id: 332, setName: "Moon Hunter", effects: [] },
  { id: 333, setName: "Savage Werewolf", effects: [] },
  { id: 334, setName: "Jailer's Tenacity", effects: [] },
  { id: 335, setName: "Vykosa", effects: [] },
  { id: 336, setName: "Hanu's Compassion", effects: [] },
  { id: 337, setName: "Blood Moon", effects: [] },
  { id: 338, setName: "Haven of Ursus", effects: [] },
  { id: 339, setName: "Balorgh", effects: [] },
  { id: 340, setName: "Radial Uppercut", effects: [] },
  { id: 341, setName: "Mender's Ward", effects: [] },
  { id: 342, setName: "Indomitable Fury", effects: [] },
  { id: 343, setName: "Spell Strategist", effects: [] },
  { id: 344, setName: "Battlefield Acrobat", effects: [] },
  { id: 345, setName: "Soldier of Anguish", effects: [] },
  { id: 346, setName: "Steadfast Hero", effects: [] },
  { id: 347, setName: "Battalion Defender", effects: [] },
  { id: 348, setName: "Bright-Throat's Boast", effects: [] },
  { id: 349, setName: "Dead-Water's Guile", effects: [] },
  { id: 350, setName: "Champion of the Hist", effects: [] },
  { id: 351, setName: "Grave-Stake Collector", effects: [] },
  { id: 352, setName: "Naga Shaman", effects: [] },
  { id: 353, setName: "Might of the Lost Legion", effects: [] },
  { id: 354, setName: "Perfected Radial Uppercut", effects: [] },
  { id: 355, setName: "Gallant Charge", effects: [] },
  { id: 356, setName: "Perfected Gallant Charge", effects: [] },
  { id: 357, setName: "Spectral Cloak", effects: [] },
  { id: 358, setName: "Perfected Spectral Cloak", effects: [] },
  { id: 359, setName: "Virulent Shot", effects: [] },
  { id: 360, setName: "Perfected Virulent Shot", effects: [] },
  { id: 361, setName: "Wild Impulse", effects: [] },
  { id: 362, setName: "Perfected Wild Impulse", effects: [] },
  { id: 363, setName: "Perfected Mender's Ward", effects: [] },
  { id: 364, setName: "Icy Conjurer", effects: [] },
  { id: 365, setName: "Tzogvin's Warband", effects: [] },
  { id: 366, setName: "Mighty Glacier", effects: [] },
  { id: 367, setName: "Stonekeeper", effects: [] },
  { id: 368, setName: "Auroran's Thunder", effects: [] },
  { id: 369, setName: "Scavenging Demise", effects: [] },
  { id: 370, setName: "Frozen Watcher", effects: [] },
  { id: 371, setName: "Symphony of Blades", effects: [] },
  { id: 372, setName: "Vastarie's Tutelage", effects: [] },
  { id: 373, setName: "Crafty Alfiq", effects: [] },
  { id: 374, setName: "Vesture of Darloc Brae", effects: [] },
  { id: 375, setName: "Call of the Undertaker", effects: [] },
  { id: 376, setName: "False God's Devotion", effects: [] },
  { id: 377, setName: "Coldharbour's Favorite", effects: [] },
  { id: 378, setName: "Senche-Raht's Grit", effects: [] },
  { id: 379, setName: "Tooth of Lokkestiiz", effects: [] },
  { id: 380, setName: "Eye of Nahviintaas", effects: [] },
  { id: 381, setName: "Claw of Yolnahkriin", effects: [] },
  { id: 382, setName: "Perfected Tooth of Lokkestiiz", effects: [] },
  { id: 383, setName: "Perfected Claw of Yolnahkriin", effects: [] },
  { id: 384, setName: "Perfected Eye of Nahviintaas", effects: [] },
  { id: 385, setName: "Perfected False God's Devotion", effects: [] },
  { id: 386, setName: "Hollowfang Thirst", effects: [] },
  { id: 387, setName: "Dro'Zakar's Claws", effects: [] },
  { id: 388, setName: "Renald's Resolve Set", effects: [] },
  { id: 389, setName: "Grundwulf", effects: [] },
  { id: 390, setName: "Z'en's Redress", effects: [] },
  { id: 391, setName: "Azureblight Reaper", effects: [] },
  { id: 392, setName: "Dragon's Defilement", effects: [] },
  { id: 393, setName: "Maarselok", effects: [] },
  { id: 394, setName: "Marauder's Haste", effects: [] },
  { id: 395, setName: "Dragonguard Elite", effects: [] },
  { id: 396, setName: "Senchal Defender", effects: [] },
  { id: 397, setName: "Ancient Dragonguard", effects: [] },
  { id: 398, setName: "Daring Corsair", effects: [] },
  { id: 399, setName: "New Moon Acolyte", effects: [] },
  { id: 400, setName: "Hiti's Hearth", effects: [] },
  { id: 401, setName: "Titanborn Strength", effects: [] },
  { id: 402, setName: "Bani's Torment", effects: [] },
  { id: 403, setName: "Mother Ciannait", effects: [] },
  { id: 404, setName: "Draugrkin's Grip", effects: [] },
  { id: 405, setName: "Aegis Caller", effects: [] },
  { id: 406, setName: "Grave Guardian", effects: [] },
  { id: 407, setName: "Kjalnar's Nightmare", effects: [] },
  { id: 408, setName: "Critical Riposte", effects: [] },
  { id: 409, setName: "Unchained Aggressor", effects: [] },
  { id: 410, setName: "Dauntless Combatant", effects: [] },
  { id: 411, setName: "Winter's Respite", effects: [] },
  { id: 412, setName: "Venomous Smite", effects: [] },
  { id: 413, setName: "Eternal Vigor", effects: [] },
  { id: 414, setName: "Stuhn's Favor", effects: [] },
  { id: 415, setName: "Dragon's Appetite", effects: [] },
  { id: 416, setName: "Kyne's Wind", effects: [] },
  { id: 417, setName: "Perfected Kyne's Wind", effects: [] },
  { id: 418, setName: "Vrol's Command", effects: [] },
  { id: 419, setName: "Perfected Vrol's Command", effects: [] },
  { id: 420, setName: "Roaring Opportunist", effects: [] },
  { id: 421, setName: "Perfected Roaring Opportunist", effects: [] },
  { id: 422, setName: "Yandir's Might", effects: [] },
  { id: 423, setName: "Perfected Yandir's Might", effects: [] },
  { id: 424, setName: "Thrassian Stranglers", effects: [] },
  { id: 425, setName: "Ring of the Wild Hunt", effects: [] },
  { id: 426, setName: "Torc of Tonal Constancy", effects: [] },
  { id: 427, setName: "Spell Parasite", effects: [] },
  { id: 428, setName: "Perfected Titanic Cleave", effects: [] },
  { id: 429, setName: "Perfected Puncturing Remedy", effects: [] },
  { id: 430, setName: "Perfected Stinging Slashes", effects: [] },
  { id: 431, setName: "Perfected Caustic Arrow", effects: [] },
  { id: 432, setName: "Perfected Destructive Impact", effects: [] },
  { id: 433, setName: "Perfected Grand Rejuvenation", effects: [] },
  { id: 434, setName: "Snow Treaders", effects: [] },
  { id: 435, setName: "Malacath's Band of Brutality", effects: [] },
  { id: 436, setName: "Bloodlord's Embrace", effects: [] },
  { id: 437, setName: "Perfected Merciless Charge", effects: [] },
  { id: 438, setName: "Perfected Rampaging Slash", effects: [] },
  { id: 439, setName: "Perfected Cruel Flurry", effects: [] },
  { id: 440, setName: "Perfected Thunderous Volley", effects: [] },
  { id: 441, setName: "Perfected Crushing Wall", effects: [] },
  { id: 442, setName: "Perfected Precise Regeneration", effects: [] },
  { id: 443, setName: "The Destruction Suite", effects: [] },
  { id: 444, setName: "Relics of the Physician, Ansur", effects: [] },
  { id: 445, setName: "Treasures of the Earthforge", effects: [] },
  { id: 446, setName: "Relics of the Rebellion", effects: [] },
  { id: 447, setName: "Arms of Infernace", effects: [] },
  { id: 448, setName: "Arms of the Ancestors", effects: [] },
  { id: 449, setName: "Armor of the Code", effects: [] },
  { id: 450, setName: "Giant Spider", effects: [] },
  { id: 451, setName: "Prophet's", effects: [] },
  { id: 452, setName: "Broken Soul", effects: [] },
  { id: 453, setName: "Talfyg's Treachery", effects: [] },
  { id: 454, setName: "Unleashed Terror", effects: [] },
  { id: 455, setName: "Crimson Twilight", effects: [] },
  { id: 456, setName: "Elemental Catalyst", effects: [] },
  { id: 457, setName: "Kraglen's Howl", effects: [] },
  { id: 458, setName: "Arkasis's Genius", effects: [] },
  { id: 459, setName: "Stone Husk", effects: [] },
  { id: 460, setName: "Lady Thorn", effects: [] },
  { id: 461, setName: "Pearls of Ehlnofey", effects: [] },
  { id: 462, setName: "Radiant Bastion", effects: [] },
  { id: 463, setName: "Voidcaller", effects: [] },
  { id: 464, setName: "Witch-Knight's Defiance", effects: [] },
  { id: 465, setName: "Red Eagle's Fury", effects: [] },
  { id: 466, setName: "Legacy of Karth", effects: [] },
  { id: 467, setName: "Aetherial Ascension", effects: [] },
  { id: 468, setName: "Hex Siphon", effects: [] },
  { id: 469, setName: "Pestilent Host", effects: [] },
  { id: 470, setName: "Explosive Rebuke", effects: [] },
  { id: 471, setName: "Executioner's Blade", effects: [] },
  { id: 472, setName: "Void Bash", effects: [] },
  { id: 473, setName: "Frenzied Momentum", effects: [] },
  { id: 474, setName: "Point-Blank Snipe", effects: [] },
  { id: 475, setName: "Wrath of Elements", effects: [] },
  { id: 476, setName: "Force Overflow", effects: [] },
  { id: 477, setName: "Perfected Executioner's Blade", effects: [] },
  { id: 478, setName: "Perfected Void Bash", effects: [] },
  { id: 479, setName: "Perfected Frenzied Momentum", effects: [] },
  { id: 480, setName: "Perfected Point-Blank Snipe", effects: [] },
  { id: 481, setName: "Perfected Wrath of Elements", effects: [] },
  { id: 482, setName: "Perfected Force Overflow", effects: [] },
  { id: 483, setName: "Ring of the Pale Order", effects: [] },
  { id: 484, setName: "Baron Zaudrus", effects: [] },
  { id: 485, setName: "Encratis's Behemoth", effects: [] },
  { id: 486, setName: "True-Sworn Fury", effects: [] },
  { id: 487, setName: "Kinras's Wrath", effects: [] },
  { id: 488, setName: "Drake's Rush", effects: [] },
  { id: 489, setName: "Unleashed Ritualist", effects: [] },
  { id: 490, setName: "Dagon's Dominion", effects: [] },
  { id: 491, setName: "Foolkiller's Ward", effects: [] },
  { id: 492, setName: "Frostbite", effects: [] },
  { id: 493, setName: "Deadlands Assassin", effects: [] },
  { id: 494, setName: "Bog Raider", effects: [] },
  { id: 495, setName: "Hist Whisperer", effects: [] },
  { id: 496, setName: "Heartland Conqueror", effects: [] },
  { id: 497, setName: "Diamond's Victory", effects: [] },
  { id: 498, setName: "Saxhleel Champion", effects: [] },
  { id: 499, setName: "Sul-Xan's Torment", effects: [] },
  { id: 500, setName: "Bahsei's Mania", effects: [] },
  { id: 501, setName: "Stone-Talker's Oath", effects: [] },
  { id: 502, setName: "Perfected Saxhleel Champion", effects: [] },
  { id: 503, setName: "Perfected Sul-Xan's Torment", effects: [] },
  { id: 504, setName: "Perfected Bahsei's Mania", effects: [] },
  { id: 505, setName: "Perfected Stone-Talker's Oath", effects: [] },
  { id: 506, setName: "Gaze of Sithis", effects: [] },
  { id: 507, setName: "Harpooner's Wading Kilt", effects: [] },
  { id: 508, setName: "Harvester's Hope-Ring", effects: [] },
  { id: 509, setName: "Death Dealer's Fete", effects: [] },
  { id: 510, setName: "Shapeshifter's Chain", effects: [] },
  { id: 511, setName: "Zoal the Ever-Wakeful", effects: [] },
  { id: 512, setName: "Immolator Charr", effects: [] },
  { id: 513, setName: "Glorgoloch the Destroyer", effects: [] },
  { id: 514, setName: "Silver Rose Vigil", effects: [] },
  { id: 515, setName: "Thunder Caller", effects: [] },
  { id: 516, setName: "Crimson Oath's Rive", effects: [] },
  { id: 517, setName: "Rush of Agony", effects: [] },
  { id: 518, setName: "Scorion's Feast", effects: [] },
  { id: 519, setName: "Magma Incarnate", effects: [] },
  { id: 520, setName: "Grisly Gourmet", effects: [] },
  { id: 521, setName: "Prior Thierric", effects: [] },
  { id: 522, setName: "Plaguebreak", effects: [] },
  { id: 523, setName: "Hrothgar's Chill", effects: [] },
  { id: 524, setName: "Dark Convergence", effects: [] },
  { id: 525, setName: "Wretched Vitality", effects: [] },
  { id: 526, setName: "Deadlands Demolisher", effects: [] },
  { id: 527, setName: "Iron Flask", effects: [] },
  { id: 528, setName: "Eye of the Grasp", effects: [] },
  { id: 529, setName: "Hexos' Ward", effects: [] },
  { id: 530, setName: "Kynmarcher's Cruelty", effects: [] },
  { id: 531, setName: "Markyn Ring of Majesty", effects: [] },
  { id: 532, setName: "Belharza's Band", effects: [] },
  { id: 533, setName: "Spaulder of Ruin", effects: [] },
  { id: 534, setName: "Spriggan's Vigor", effects: [] },
  { id: 535, setName: "Storm-Cursed's Revenge", effects: [] },
  { id: 536, setName: "Maligalig's Maelstrom", effects: [] },
  { id: 537, setName: "Gryphon's Reprisal", effects: [] },
  { id: 538, setName: "Turning Tide", effects: [] },
  { id: 539, setName: "Glacial Guardian", effects: [] },
  { id: 540, setName: "Nazaray", effects: [] },
  { id: 541, setName: "Kargaeda", effects: [] },
  { id: 542, setName: "Rallying Cry", effects: [] },
  { id: 543, setName: "Hew and Sunder", effects: [] },
  { id: 544, setName: "Enervating Aura", effects: [] },
  { id: 545, setName: "Nunatak", effects: [] },
  { id: 546, setName: "Lady Malygda", effects: [] },
  { id: 547, setName: "Baron Thirsk", effects: [] },
  { id: 548, setName: "Order's Wrath", effects: [] },
  { id: 549, setName: "Oakensoul Ring", effects: [] },
  { id: 550, setName: "Sea-Serpent's Coil", effects: [] },
  { id: 551, setName: "Lefthander's Aegis Belt", effects: [] },
  { id: 552, setName: "Dov-Rha Sabatons", effects: [] },
  { id: 553, setName: "Mora's Whispers", effects: [] },
  { id: 554, setName: "Perfected Pearlescent Ward", effects: [] },
  { id: 555, setName: "Perfected Coral Riptide", effects: [] },
  { id: 556, setName: "Perfected Whorl of the Depths", effects: [] },
  { id: 557, setName: "Perfected Pillager's Profit", effects: [] },
  { id: 558, setName: "Pillager's Profit", effects: [] },
  { id: 559, setName: "Pearlescent Ward", effects: [] },
  { id: 560, setName: "Coral Riptide", effects: [] },
  { id: 561, setName: "Whorl of the Depths", effects: [] },
  { id: 562, setName: "Systres' Scowl", effects: [] },
  { id: 563, setName: "Steadfast's Mettle", effects: [] },
  { id: 564, setName: "Blessing of High Isle", effects: [] },
  { id: 565, setName: "Druid's Braid", effects: [] },
  { id: 566, setName: "Serpent's Disdain", effects: [] },
  { id: 567, setName: "Languor of Peryite", effects: [] },
  { id: 568, setName: "Nocturnal's Ploy", effects: [] },
  { id: 569, setName: "Mara's Balm", effects: [] },
  { id: 570, setName: "Stone's Accord", effects: [] },
  { id: 571, setName: "Rage of the Ursauk", effects: [] },
  { id: 572, setName: "Deeproot Zeal", effects: [] },
  { id: 573, setName: "Archdruid Devyric", effects: [] },
  { id: 574, setName: "Grave Inevitability", effects: [] },
  { id: 575, setName: "Phylactery's Grasp", effects: [] },
  { id: 576, setName: "Pangrit Denmother", effects: [] },
  { id: 577, setName: "Euphotic Gatekeeper", effects: [] },
  { id: 578, setName: "Back-Alley Gourmand", effects: [] },
  { id: 579, setName: "Phoenix Moth Theurge", effects: [] },
  { id: 580, setName: "Bastion of the Draoife", effects: [] },
  { id: 581, setName: "Faun's Lark Cladding", effects: [] },
  { id: 582, setName: "Stormweaver's Cavort", effects: [] },
  { id: 583, setName: "Syrabane's Ward", effects: [] },
  { id: 584, setName: "Chimera's Rebuke", effects: [] },
  { id: 585, setName: "Old Growth Brewer", effects: [] },
  { id: 586, setName: "Claw of the Forest Wraith", effects: [] },
  { id: 587, setName: "Roksa the Warped", effects: [] },
  { id: 588, setName: "Ozezan the Inferno", effects: [] },
  { id: 589, setName: "Snake in the Stars", effects: [] },
  { id: 590, setName: "Abyssal Brace", effects: [] },
  { id: 591, setName: "Shell Splitter", effects: [] },
  { id: 592, setName: "Telvanni Enforcer", effects: [] },
  { id: 593, setName: "Nix-Hound's Howl", effects: [] },
  { id: 594, setName: "Apocryphal Inspiration", effects: [] },
  { id: 595, setName: "Ritemaster's Bond", effects: [] },
  { id: 596, setName: "Runecarver's Blaze", effects: [] },
  { id: 597, setName: "Judgment of Akatosh", effects: [] },
  { id: 598, setName: "Cryptcanon Vestments", effects: [] },
  { id: 599, setName: "Esoteric Environment Greaves Set", effects: [] },
  { id: 600, setName: "Velothi Ur-Mage's Amulet", effects: [] },
  { id: 601, setName: "Transformative Hope", effects: [] },
  { id: 602, setName: "Peace and Serenity", effects: [] },
  { id: 603, setName: "Ansuul's Torment", effects: [] },
  { id: 604, setName: "Perfected Test of Resolve Set", effects: [] },
  { id: 605, setName: "Shattered Fate", effects: [] },
  { id: 606, setName: "Telvanni Efficiency", effects: [] },
  { id: 607, setName: "Seeker Synthesis", effects: [] },
  { id: 608, setName: "Vivec's Duality", effects: [] },
  { id: 609, setName: "Camonna Tong", effects: [] },
  { id: 610, setName: "Adamant Lurker", effects: [] },
  { id: 611, setName: "Test of Resolve Set", effects: [] },
  { id: 612, setName: "Perfected Transformative Hope", effects: [] },
  { id: 613, setName: "Perfected Ansuul's Torment", effects: [] },
  { id: 614, setName: "Perfected Peace and Serenity", effects: [] },
  { id: 615, setName: "Jerall Mountains Warchief", effects: [] },
  { id: 616, setName: "Nibenay Bay Battlereeve", effects: [] },
  { id: 617, setName: "Colovian Highlands General", effects: [] },
  { id: 618, setName: "Wrathsun", effects: [] },
  { id: 619, setName: "Reawakened Hierophant", effects: [] },
  { id: 620, setName: "Soulcleaver", effects: [] },
  { id: 621, setName: "Monolith of Storms", effects: [] },
  { id: 622, setName: "Basalt-Blooded Warrior", effects: [] },
  { id: 623, setName: "Nobility in Decay", effects: [] },
  { id: 624, setName: "Gardener of Seasons", effects: [] },
  { id: 625, setName: "Torc of the Last Ayleid King", effects: [] },
  { id: 626, setName: "The Blind", effects: [] },
  { id: 627, setName: "Black-Glove Grounding", effects: [] },
  { id: 628, setName: "Sluthrug's Hunger", effects: [] },
  { id: 629, setName: "Tarnished Nightmare", effects: [] },
  { id: 630, setName: "Reflected Fury", effects: [] },
  { id: 631, setName: "Cinders of Anthelmir", effects: [] },
  { id: 632, setName: "Blind Path Induction", effects: [] },
  { id: 633, setName: "Oakfather's Retribution", effects: [] },
  { id: 634, setName: "Anthelmir's Construct", effects: [] },
  { id: 635, setName: "Blunted Blades", effects: [] },
  { id: 636, setName: "Baan Dar's Blessing", effects: [] },
  { id: 637, setName: "Xoryn's Masterpiece", effects: [] },
  { id: 638, setName: "Mora Scribe's Thesis", effects: [] },
  { id: 639, setName: "Slivers of the Null Arca", effects: [] },
  { id: 640, setName: "Lucent Echoes", effects: [] },
  { id: 641, setName: "Ayleid Refuge", effects: [] },
  { id: 642, setName: "Symmetry of the Weald", effects: [] },
  { id: 643, setName: "Macabre Vintage", effects: [] },
  { id: 644, setName: "The Saint and the Seducer", effects: [] },
  { id: 645, setName: "Rourken Steamguards", effects: [] },
  { id: 646, setName: "The Shadow Queen's Cowl", effects: [] },
  { id: 647, setName: "Highland Sentinel", effects: [] },
  { id: 648, setName: "Tharriker's Strike", effects: [] },
  { id: 649, setName: "Threads of War", effects: [] },
  { id: 650, setName: "Perfected Xoryn's Masterpiece", effects: [] },
  { id: 651, setName: "Perfected Lucent Echoes", effects: [] },
  { id: 652, setName: "Perfected Slivers of the Null Arca", effects: [] },
  { id: 653, setName: "Perfected Mora Scribe's Thesis", effects: [] },
  { id: 654, setName: "Aerie's Cry", effects: [] },
  { id: 655, setName: "Aetheric Lancer", effects: [] },
  { id: 656, setName: "Beacon of Oblivion", effects: [] },
  { id: 657, setName: "Pyrebrand", effects: [] },
  { id: 658, setName: "Spattering Disjunction", effects: [] },
  { id: 659, setName: "Umbral Edge", effects: [] },
  { id: 660, setName: "Corpseburster", effects: [] },
  { id: 661, setName: "Tracker's Lash", effects: [] },
  { id: 662, setName: "Netch Oil", effects: [] },
  { id: 663, setName: "Shared Pain", effects: [] },
  { id: 664, setName: "Siegemaster's Focus", effects: [] },
  { id: 665, setName: "Bulwark Ruination", effects: [] },
  { id: 666, setName: "Farstrider", effects: [] },
  { id: 667, setName: "Vandorallen's Resonance Set", effects: [] },
  { id: 668, setName: "Orpheon the Tactician", effects: [] },
  { id: 669, setName: "Squall of Retribution", effects: [] },
  { id: 670, setName: "Heroic Unity", effects: [] },
  { id: 671, setName: "Noxious Boulder", effects: [] },
  { id: 672, setName: "Jerensi's Bladestorm", effects: [] },
  { id: 673, setName: "Fledgling's Nest", effects: [] },
  { id: 674, setName: "Lucilla's Windshield", effects: [] },
  { id: 675, setName: "Arkay's Charity", effects: [] },
  { id: 676, setName: "Lamp Knight's Art", effects: [] },
  { id: 677, setName: "Blackfeather Flight", effects: [] },
  { id: 678, setName: "Three Queens Wellspring", effects: [] },
  { id: 679, setName: "Death-Dancer", effects: [] },
  { id: 680, setName: "Full Belly Barricade", effects: [] },
  { id: 681, setName: "Shared Burden", effects: [] },
  { id: 682, setName: "Tide-Born Wildstalker", effects: [] },
  { id: 683, setName: "Fellowship's Fortitude", effects: [] },
  { id: 684, setName: "Mad God's Dancing Shoes", effects: [] },
  { id: 685, setName: "Rakkhat's Voidmantle", effects: [] },
  { id: 686, setName: "Monomyth Reforged", effects: [] },
  { id: 687, setName: "Harmony in Chaos", effects: [] },
  { id: 688, setName: "Kazpian's Cruel Signet", effects: [] },
  { id: 689, setName: "Dolorous Arena", effects: [] },
  { id: 690, setName: "Recovery Convergence", effects: [] },
  { id: 691, setName: "Perfected Recovery Convergence", effects: [] },
  { id: 692, setName: "Perfected Dolorous Arena", effects: [] },
  { id: 693, setName: "Perfected Kazpian's Cruel Signet", effects: [] },
  { id: 694, setName: "Perfected Harmony in Chaos", effects: [] },
  { id: 695, setName: "Bar-Sakka", effects: [] },
  { id: 696, setName: "Xanmeer Spellweaver", effects: [] },
  { id: 697, setName: "Black Foundry Steel", effects: [] },
  { id: 698, setName: "Vykand's Soulfury", effects: [] },
  { id: 699, setName: "Lustrous Soulwell", effects: [] },
  { id: 700, setName: "Stonehulk Domination", effects: [] },
  { id: 701, setName: "Tools of the Trapmaster", effects: [] },
  { id: 702, setName: "Black Gem Monstrosity", effects: [] },
  { id: 703, setName: "Coup De Grâce", effects: [] },
  { id: 704, setName: "Spellshredder", effects: [] },
  { id: 705, setName: "Unflinching Ultimate", effects: [] },
  { id: 706, setName: "Huntsman's Warmask", effects: [] },
  { id: 707, setName: "Xanmeer Genesis", effects: [] },
  { id: 708, setName: "Shattered Paths Signet", effects: [] },
  { id: 709, setName: "Glittering Goad", effects: [] },
  { id: 710, setName: "Thousand Eyes", effects: [] },
  { id: 711, setName: "The Ruckus", effects: [] },
  { id: 712, setName: "Gorethief", effects: [] },
  { id: 713, setName: "Prowler's Talisman", effects: [] },
  { id: 714, setName: "Tarcyr", effects: [] },
  { id: 715, setName: "Mylenne Moon-Caller", effects: [] },
];
