import { CommonSkillLine, ClassSkillLine, type SkillAbility } from './raidTemplate';

export const ESO_SKILLS: SkillAbility[] = [
{ id: 1, skillLine: CommonSkillLine.FightersGuild, skillName: "Dawnbreaker", isUltimate: true, parentSkillName: null },
{ id: 2, skillLine: CommonSkillLine.FightersGuild, skillName: "Dawnbreaker of Smiting", isUltimate: true, parentSkillName: "Dawnbreaker" },
{ id: 3, skillLine: CommonSkillLine.FightersGuild, skillName: "Flawless Dawnbreaker", isUltimate: true, parentSkillName: "Dawnbreaker" },
{ id: 4, skillLine: CommonSkillLine.FightersGuild, skillName: "Silver Bolts", isUltimate: false, parentSkillName: null },
{ id: 5, skillLine: CommonSkillLine.FightersGuild, skillName: "Silver Leash", isUltimate: false, parentSkillName: "Silver Bolts" },
{ id: 6, skillLine: CommonSkillLine.FightersGuild, skillName: "Silver Shards", isUltimate: false, parentSkillName: "Silver Bolts" },
{ id: 7, skillLine: CommonSkillLine.FightersGuild, skillName: "Circle of Protection", isUltimate: false, parentSkillName: null },
{ id: 8, skillLine: CommonSkillLine.FightersGuild, skillName: "Ring of Preservation", isUltimate: false, parentSkillName: "Circle of Protection" },
{ id: 9, skillLine: CommonSkillLine.FightersGuild, skillName: "Turn Evil", isUltimate: false, parentSkillName: "Circle of Protection" },
{ id: 10, skillLine: CommonSkillLine.FightersGuild, skillName: "Expert Hunter", isUltimate: false, parentSkillName: null },
{ id: 11, skillLine: CommonSkillLine.FightersGuild, skillName: "Camouflaged Hunter", isUltimate: false, parentSkillName: "Expert Hunter" },
{ id: 12, skillLine: CommonSkillLine.FightersGuild, skillName: "Evil Hunter", isUltimate: false, parentSkillName: "Expert Hunter" },
{ id: 13, skillLine: CommonSkillLine.FightersGuild, skillName: "Trap Beast", isUltimate: false, parentSkillName: null },
{ id: 14, skillLine: CommonSkillLine.FightersGuild, skillName: "Barbed Trap", isUltimate: false, parentSkillName: "Trap Beast" },
{ id: 15, skillLine: CommonSkillLine.FightersGuild, skillName: "Lightweight Beast Trap", isUltimate: false, parentSkillName: "Trap Beast" },

{ id: 21, skillLine: CommonSkillLine.MagesGuild, skillName: "Meteor", isUltimate: true, parentSkillName: null },
{ id: 22, skillLine: CommonSkillLine.MagesGuild, skillName: "Ice Comet", isUltimate: true, parentSkillName: "Meteor" },
{ id: 23, skillLine: CommonSkillLine.MagesGuild, skillName: "Shooting Star", isUltimate: true, parentSkillName: "Meteor" },
{ id: 24, skillLine: CommonSkillLine.MagesGuild, skillName: "Magelight", isUltimate: false, parentSkillName: null },
{ id: 25, skillLine: CommonSkillLine.MagesGuild, skillName: "Inner Light", isUltimate: false, parentSkillName: "Magelight" },
{ id: 26, skillLine: CommonSkillLine.MagesGuild, skillName: "Radiant Magelight", isUltimate: false, parentSkillName: "Magelight" },
{ id: 27, skillLine: CommonSkillLine.MagesGuild, skillName: "Entropy", isUltimate: false, parentSkillName: null },
{ id: 28, skillLine: CommonSkillLine.MagesGuild, skillName: "Degeneration", isUltimate: false, parentSkillName: "Entropy" },
{ id: 29, skillLine: CommonSkillLine.MagesGuild, skillName: "Structured Entropy", isUltimate: false, parentSkillName: "Entropy" },
{ id: 30, skillLine: CommonSkillLine.MagesGuild, skillName: "Fire Rune", isUltimate: false, parentSkillName: null },
{ id: 31, skillLine: CommonSkillLine.MagesGuild, skillName: "Scalding Rune", isUltimate: false, parentSkillName: "Fire Rune" },
{ id: 32, skillLine: CommonSkillLine.MagesGuild, skillName: "Volcanic Rune", isUltimate: false, parentSkillName: "Fire Rune" },
{ id: 33, skillLine: CommonSkillLine.MagesGuild, skillName: "Equilibrium", isUltimate: false, parentSkillName: null },
{ id: 34, skillLine: CommonSkillLine.MagesGuild, skillName: "Balance", isUltimate: false, parentSkillName: "Equilibrium" },
{ id: 35, skillLine: CommonSkillLine.MagesGuild, skillName: "Spell Symmetry", isUltimate: false, parentSkillName: "Equilibrium" },

{ id: 41, skillLine: CommonSkillLine.Undaunted, skillName: "Blood Altar", isUltimate: false, parentSkillName: null },
{ id: 42, skillLine: CommonSkillLine.Undaunted, skillName: "Overflowing Altar", isUltimate: false, parentSkillName: "Blood Altar" },
{ id: 43, skillLine: CommonSkillLine.Undaunted, skillName: "Sanguine Altar", isUltimate: false, parentSkillName: "Blood Altar" },
{ id: 44, skillLine: CommonSkillLine.Undaunted, skillName: "Trapping Webs", isUltimate: false, parentSkillName: null },
{ id: 45, skillLine: CommonSkillLine.Undaunted, skillName: "Shadow Silk", isUltimate: false, parentSkillName: "Trapping Webs" },
{ id: 46, skillLine: CommonSkillLine.Undaunted, skillName: "Tangling Webs", isUltimate: false, parentSkillName: "Trapping Webs" },
{ id: 47, skillLine: CommonSkillLine.Undaunted, skillName: "Inner Fire", isUltimate: false, parentSkillName: null },
{ id: 48, skillLine: CommonSkillLine.Undaunted, skillName: "Inner Beast", isUltimate: false, parentSkillName: "Inner Fire" },
{ id: 49, skillLine: CommonSkillLine.Undaunted, skillName: "Inner Rage", isUltimate: false, parentSkillName: "Inner Fire" },
{ id: 50, skillLine: CommonSkillLine.Undaunted, skillName: "Bone Shield", isUltimate: false, parentSkillName: null },
{ id: 51, skillLine: CommonSkillLine.Undaunted, skillName: "Bone Surge", isUltimate: false, parentSkillName: "Bone Shield" },
{ id: 52, skillLine: CommonSkillLine.Undaunted, skillName: "Spiked Bone Shield", isUltimate: false, parentSkillName: "Bone Shield" },
{ id: 53, skillLine: CommonSkillLine.Undaunted, skillName: "Necrotic Orb", isUltimate: false, parentSkillName: null },
{ id: 54, skillLine: CommonSkillLine.Undaunted, skillName: "Energy Orb", isUltimate: false, parentSkillName: "Necrotic Orb" },
{ id: 55, skillLine: CommonSkillLine.Undaunted, skillName: "Mystic Orb", isUltimate: false, parentSkillName: "Necrotic Orb" },

{ id: 58, skillLine: CommonSkillLine.PsijicOrder, skillName: "Undo", isUltimate: true, parentSkillName: null },
{ id: 59, skillLine: CommonSkillLine.PsijicOrder, skillName: "Precognition", isUltimate: true, parentSkillName: "Undo" },
{ id: 60, skillLine: CommonSkillLine.PsijicOrder, skillName: "Temporal Guard", isUltimate: true, parentSkillName: "Undo" },
{ id: 61, skillLine: CommonSkillLine.PsijicOrder, skillName: "Time Stop", isUltimate: false, parentSkillName: null },
{ id: 62, skillLine: CommonSkillLine.PsijicOrder, skillName: "Borrowed Time", isUltimate: false, parentSkillName: "Time Stop" },
{ id: 63, skillLine: CommonSkillLine.PsijicOrder, skillName: "Time Freeze", isUltimate: false, parentSkillName: "Time Stop" },
{ id: 64, skillLine: CommonSkillLine.PsijicOrder, skillName: "Imbue Weapon", isUltimate: false, parentSkillName: null },
{ id: 65, skillLine: CommonSkillLine.PsijicOrder, skillName: "Crushing Weapon", isUltimate: false, parentSkillName: "Imbue Weapon" },
{ id: 66, skillLine: CommonSkillLine.PsijicOrder, skillName: "Elemental Weapon", isUltimate: false, parentSkillName: "Imbue Weapon" },
{ id: 67, skillLine: CommonSkillLine.PsijicOrder, skillName: "Accelerate", isUltimate: false, parentSkillName: null },
{ id: 68, skillLine: CommonSkillLine.PsijicOrder, skillName: "Channeled Acceleration", isUltimate: false, parentSkillName: "Accelerate" },
{ id: 69, skillLine: CommonSkillLine.PsijicOrder, skillName: "Race Against Time", isUltimate: false, parentSkillName: "Accelerate" },
{ id: 70, skillLine: CommonSkillLine.PsijicOrder, skillName: "Mend Wounds", isUltimate: false, parentSkillName: null },
{ id: 71, skillLine: CommonSkillLine.PsijicOrder, skillName: "Mend Spirit", isUltimate: false, parentSkillName: "Mend Wounds" },
{ id: 72, skillLine: CommonSkillLine.PsijicOrder, skillName: "Symbiosis", isUltimate: false, parentSkillName: "Mend Wounds" },
{ id: 73, skillLine: CommonSkillLine.PsijicOrder, skillName: "Meditate", isUltimate: false, parentSkillName: null },
{ id: 74, skillLine: CommonSkillLine.PsijicOrder, skillName: "Deep Thoughts", isUltimate: false, parentSkillName: "Meditate" },
{ id: 75, skillLine: CommonSkillLine.PsijicOrder, skillName: "Introspection", isUltimate: false, parentSkillName: "Meditate" },

{ id: 81, skillLine: CommonSkillLine.Vampire, skillName: "Blood Scion", isUltimate: true, parentSkillName: null },
{ id: 82, skillLine: CommonSkillLine.Vampire, skillName: "Perfect Scion", isUltimate: true, parentSkillName: "Blood Scion" },
{ id: 83, skillLine: CommonSkillLine.Vampire, skillName: "Swarming Scion", isUltimate: true, parentSkillName: "Blood Scion" },
{ id: 84, skillLine: CommonSkillLine.Vampire, skillName: "Eviscerate", isUltimate: false, parentSkillName: null },
{ id: 85, skillLine: CommonSkillLine.Vampire, skillName: "Arterial Burst", isUltimate: false, parentSkillName: "Eviscerate" },
{ id: 86, skillLine: CommonSkillLine.Vampire, skillName: "Blood for Blood", isUltimate: false, parentSkillName: "Eviscerate" },
{ id: 87, skillLine: CommonSkillLine.Vampire, skillName: "Blood Frenzy", isUltimate: false, parentSkillName: null },
{ id: 88, skillLine: CommonSkillLine.Vampire, skillName: "Sated Fury", isUltimate: false, parentSkillName: "Blood Frenzy" },
{ id: 89, skillLine: CommonSkillLine.Vampire, skillName: "Simmering Frenzy", isUltimate: false, parentSkillName: "Blood Frenzy" },
{ id: 90, skillLine: CommonSkillLine.Vampire, skillName: "Vampiric Drain", isUltimate: false, parentSkillName: null },
{ id: 91, skillLine: CommonSkillLine.Vampire, skillName: "Drain Vigor", isUltimate: false, parentSkillName: "Vampiric Drain" },
{ id: 92, skillLine: CommonSkillLine.Vampire, skillName: "Exhilarating Drain", isUltimate: false, parentSkillName: "Vampiric Drain" },
{ id: 93, skillLine: CommonSkillLine.Vampire, skillName: "Mesmerize", isUltimate: false, parentSkillName: null },
{ id: 94, skillLine: CommonSkillLine.Vampire, skillName: "Hypnosis", isUltimate: false, parentSkillName: "Mesmerize" },
{ id: 95, skillLine: CommonSkillLine.Vampire, skillName: "Stupefy", isUltimate: false, parentSkillName: "Mesmerize" },
{ id: 96, skillLine: CommonSkillLine.Vampire, skillName: "Mist Form", isUltimate: false, parentSkillName: null },
{ id: 97, skillLine: CommonSkillLine.Vampire, skillName: "Blood Mist", isUltimate: false, parentSkillName: "Mist Form" },
{ id: 98, skillLine: CommonSkillLine.Vampire, skillName: "Elusive Mist", isUltimate: false, parentSkillName: "Mist Form" },

{ id: 105, skillLine: CommonSkillLine.Werewolf, skillName: "Werewolf Transformation", isUltimate: true, parentSkillName: null },
{ id: 106, skillLine: CommonSkillLine.Werewolf, skillName: "Pack Leader", isUltimate: true, parentSkillName: "Werewolf Transformation" },
{ id: 107, skillLine: CommonSkillLine.Werewolf, skillName: "Werewolf Berserker", isUltimate: true, parentSkillName: "Werewolf Transformation" },
{ id: 108, skillLine: CommonSkillLine.Werewolf, skillName: "Pounce", isUltimate: false, parentSkillName: null },
{ id: 109, skillLine: CommonSkillLine.Werewolf, skillName: "Brutal Pounce", isUltimate: false, parentSkillName: "Pounce" },
{ id: 110, skillLine: CommonSkillLine.Werewolf, skillName: "Feral Pounce", isUltimate: false, parentSkillName: "Pounce" },
{ id: 111, skillLine: CommonSkillLine.Werewolf, skillName: "Hircine's Bounty", isUltimate: false, parentSkillName: null },
{ id: 112, skillLine: CommonSkillLine.Werewolf, skillName: "Hircine's Fortitude", isUltimate: false, parentSkillName: "Hircine's Bounty" },
{ id: 113, skillLine: CommonSkillLine.Werewolf, skillName: "Hircine's Rage", isUltimate: false, parentSkillName: "Hircine's Bounty" },
{ id: 114, skillLine: CommonSkillLine.Werewolf, skillName: "Roar", isUltimate: false, parentSkillName: null },
{ id: 115, skillLine: CommonSkillLine.Werewolf, skillName: "Deafening Roar", isUltimate: false, parentSkillName: "Roar" },
{ id: 116, skillLine: CommonSkillLine.Werewolf, skillName: "Ferocious Roar", isUltimate: false, parentSkillName: "Roar" },
{ id: 117, skillLine: CommonSkillLine.Werewolf, skillName: "Gnash", isUltimate: false, parentSkillName: null },
{ id: 118, skillLine: CommonSkillLine.Werewolf, skillName: "Bloody Gnash", isUltimate: false, parentSkillName: "Gnash" },
{ id: 119, skillLine: CommonSkillLine.Werewolf, skillName: "Rip and Tear", isUltimate: false, parentSkillName: "Gnash" },
{ id: 120, skillLine: CommonSkillLine.Werewolf, skillName: "Rending Claws", isUltimate: false, parentSkillName: null },
{ id: 121, skillLine: CommonSkillLine.Werewolf, skillName: "Bloodclaws", isUltimate: false, parentSkillName: "Rending Claws" },
{ id: 122, skillLine: CommonSkillLine.Werewolf, skillName: "Claw Fury", isUltimate: false, parentSkillName: "Rending Claws" },

{ id: 129, skillLine: CommonSkillLine.OneHanded, skillName: "Shield Wall", isUltimate: true, parentSkillName: null },
{ id: 130, skillLine: CommonSkillLine.OneHanded, skillName: "Shield Discipline", isUltimate: true, parentSkillName: "Shield Wall" },
{ id: 131, skillLine: CommonSkillLine.OneHanded, skillName: "Spell Wall", isUltimate: true, parentSkillName: "Shield Wall" },
{ id: 132, skillLine: CommonSkillLine.OneHanded, skillName: "Shield Throw", isUltimate: false, parentSkillName: null },
{ id: 133, skillLine: CommonSkillLine.OneHanded, skillName: "Puncture", isUltimate: false, parentSkillName: null },
{ id: 134, skillLine: CommonSkillLine.OneHanded, skillName: "Pierce Armor", isUltimate: false, parentSkillName: "Puncture" },
{ id: 135, skillLine: CommonSkillLine.OneHanded, skillName: "Ransack", isUltimate: false, parentSkillName: "Puncture" },
{ id: 136, skillLine: CommonSkillLine.OneHanded, skillName: "Low Slash", isUltimate: false, parentSkillName: null },
{ id: 137, skillLine: CommonSkillLine.OneHanded, skillName: "Deep Slash", isUltimate: false, parentSkillName: "Low Slash" },
{ id: 138, skillLine: CommonSkillLine.OneHanded, skillName: "Heroic Slash", isUltimate: false, parentSkillName: "Low Slash" },
{ id: 139, skillLine: CommonSkillLine.OneHanded, skillName: "Defensive Posture", isUltimate: false, parentSkillName: null },
{ id: 140, skillLine: CommonSkillLine.OneHanded, skillName: "Absorb Missile", isUltimate: false, parentSkillName: "Defensive Posture" },
{ id: 141, skillLine: CommonSkillLine.OneHanded, skillName: "Defensive Stance", isUltimate: false, parentSkillName: "Defensive Posture" },
{ id: 142, skillLine: CommonSkillLine.OneHanded, skillName: "Shield Charge", isUltimate: false, parentSkillName: null },
{ id: 143, skillLine: CommonSkillLine.OneHanded, skillName: "Invasion", isUltimate: false, parentSkillName: "Shield Charge" },
{ id: 144, skillLine: CommonSkillLine.OneHanded, skillName: "Shielded Assault", isUltimate: false, parentSkillName: "Shield Charge" },
{ id: 145, skillLine: CommonSkillLine.OneHanded, skillName: "Power Bash", isUltimate: false, parentSkillName: null },
{ id: 146, skillLine: CommonSkillLine.OneHanded, skillName: "Power Slam", isUltimate: false, parentSkillName: "Power Bash" },
{ id: 147, skillLine: CommonSkillLine.OneHanded, skillName: "Reverberating Bash", isUltimate: false, parentSkillName: "Power Bash" },

{ id: 153, skillLine: CommonSkillLine.TwoHanded, skillName: "Berserker Strike", isUltimate: true, parentSkillName: null },
{ id: 154, skillLine: CommonSkillLine.TwoHanded, skillName: "Berserker Rage", isUltimate: true, parentSkillName: "Berserker Strike" },
{ id: 155, skillLine: CommonSkillLine.TwoHanded, skillName: "Onslaught", isUltimate: true, parentSkillName: "Berserker Strike" },
{ id: 156, skillLine: CommonSkillLine.TwoHanded, skillName: "Smash", isUltimate: false, parentSkillName: null },
{ id: 157, skillLine: CommonSkillLine.TwoHanded, skillName: "Uppercut", isUltimate: false, parentSkillName: null },
{ id: 158, skillLine: CommonSkillLine.TwoHanded, skillName: "Dizzying Swing", isUltimate: false, parentSkillName: "Uppercut" },
{ id: 159, skillLine: CommonSkillLine.TwoHanded, skillName: "Wrecking Blow", isUltimate: false, parentSkillName: "Uppercut" },
{ id: 160, skillLine: CommonSkillLine.TwoHanded, skillName: "Critical Charge", isUltimate: false, parentSkillName: null },
{ id: 161, skillLine: CommonSkillLine.TwoHanded, skillName: "Critical Rush", isUltimate: false, parentSkillName: "Critical Charge" },
{ id: 162, skillLine: CommonSkillLine.TwoHanded, skillName: "Stampede", isUltimate: false, parentSkillName: "Critical Charge" },
{ id: 163, skillLine: CommonSkillLine.TwoHanded, skillName: "Cleave", isUltimate: false, parentSkillName: null },
{ id: 164, skillLine: CommonSkillLine.TwoHanded, skillName: "Brawler", isUltimate: false, parentSkillName: "Cleave" },
{ id: 165, skillLine: CommonSkillLine.TwoHanded, skillName: "Carve", isUltimate: false, parentSkillName: "Cleave" },
{ id: 166, skillLine: CommonSkillLine.TwoHanded, skillName: "Reverse Slash", isUltimate: false, parentSkillName: null },
{ id: 167, skillLine: CommonSkillLine.TwoHanded, skillName: "Executioner", isUltimate: false, parentSkillName: "Reverse Slash" },
{ id: 168, skillLine: CommonSkillLine.TwoHanded, skillName: "Reverse Slice", isUltimate: false, parentSkillName: "Reverse Slash" },
{ id: 169, skillLine: CommonSkillLine.TwoHanded, skillName: "Momentum", isUltimate: false, parentSkillName: null },
{ id: 170, skillLine: CommonSkillLine.TwoHanded, skillName: "Forward Momentum", isUltimate: false, parentSkillName: "Momentum" },
{ id: 171, skillLine: CommonSkillLine.TwoHanded, skillName: "Rally", isUltimate: false, parentSkillName: "Momentum" },

{ id: 177, skillLine: CommonSkillLine.DualWield, skillName: "Lacerate", isUltimate: true, parentSkillName: null },
{ id: 178, skillLine: CommonSkillLine.DualWield, skillName: "Rend", isUltimate: true, parentSkillName: "Lacerate" },
{ id: 179, skillLine: CommonSkillLine.DualWield, skillName: "Thrive in Chaos", isUltimate: true, parentSkillName: "Lacerate" },
{ id: 180, skillLine: CommonSkillLine.DualWield, skillName: "Traveling Knife", isUltimate: false, parentSkillName: null },
{ id: 181, skillLine: CommonSkillLine.DualWield, skillName: "Flurry", isUltimate: false, parentSkillName: null },
{ id: 182, skillLine: CommonSkillLine.DualWield, skillName: "Bloodthirst", isUltimate: false, parentSkillName: "Flurry" },
{ id: 183, skillLine: CommonSkillLine.DualWield, skillName: "Rapid Strikes", isUltimate: false, parentSkillName: "Flurry" },
{ id: 184, skillLine: CommonSkillLine.DualWield, skillName: "Twin Slashes", isUltimate: false, parentSkillName: null },
{ id: 185, skillLine: CommonSkillLine.DualWield, skillName: "Blood Craze", isUltimate: false, parentSkillName: "Twin Slashes" },
{ id: 186, skillLine: CommonSkillLine.DualWield, skillName: "Rending Slashes", isUltimate: false, parentSkillName: "Twin Slashes" },
{ id: 187, skillLine: CommonSkillLine.DualWield, skillName: "Whirlwind", isUltimate: false, parentSkillName: null },
{ id: 188, skillLine: CommonSkillLine.DualWield, skillName: "Steel Tornado", isUltimate: false, parentSkillName: "Whirlwind" },
{ id: 189, skillLine: CommonSkillLine.DualWield, skillName: "Whirling Blades", isUltimate: false, parentSkillName: "Whirlwind" },
{ id: 190, skillLine: CommonSkillLine.DualWield, skillName: "Blade Cloak", isUltimate: false, parentSkillName: null },
{ id: 191, skillLine: CommonSkillLine.DualWield, skillName: "Deadly Cloak", isUltimate: false, parentSkillName: "Blade Cloak" },
{ id: 192, skillLine: CommonSkillLine.DualWield, skillName: "Quick Cloak", isUltimate: false, parentSkillName: "Blade Cloak" },
{ id: 193, skillLine: CommonSkillLine.DualWield, skillName: "Hidden Blade", isUltimate: false, parentSkillName: null },
{ id: 194, skillLine: CommonSkillLine.DualWield, skillName: "Flying Blade", isUltimate: false, parentSkillName: "Hidden Blade" },
{ id: 195, skillLine: CommonSkillLine.DualWield, skillName: "Shrouded Daggers", isUltimate: false, parentSkillName: "Hidden Blade" },

{ id: 201, skillLine: CommonSkillLine.Bow, skillName: "Rapid Fire", isUltimate: true, parentSkillName: null },
{ id: 202, skillLine: CommonSkillLine.Bow, skillName: "Ballista", isUltimate: true, parentSkillName: "Rapid Fire" },
{ id: 203, skillLine: CommonSkillLine.Bow, skillName: "Toxic Barrage", isUltimate: true, parentSkillName: "Rapid Fire" },
{ id: 204, skillLine: CommonSkillLine.Bow, skillName: "Vault", isUltimate: false, parentSkillName: null },
{ id: 205, skillLine: CommonSkillLine.Bow, skillName: "Snipe", isUltimate: false, parentSkillName: null },
{ id: 206, skillLine: CommonSkillLine.Bow, skillName: "Focused Aim", isUltimate: false, parentSkillName: "Snipe" },
{ id: 207, skillLine: CommonSkillLine.Bow, skillName: "Lethal Arrow", isUltimate: false, parentSkillName: "Snipe" },
{ id: 208, skillLine: CommonSkillLine.Bow, skillName: "Volley", isUltimate: false, parentSkillName: null },
{ id: 209, skillLine: CommonSkillLine.Bow, skillName: "Arrow Barrage", isUltimate: false, parentSkillName: "Volley" },
{ id: 210, skillLine: CommonSkillLine.Bow, skillName: "Endless Hail", isUltimate: false, parentSkillName: "Volley" },
{ id: 211, skillLine: CommonSkillLine.Bow, skillName: "Scatter Shot", isUltimate: false, parentSkillName: null },
{ id: 212, skillLine: CommonSkillLine.Bow, skillName: "Draining Shot", isUltimate: false, parentSkillName: "Scatter Shot" },
{ id: 213, skillLine: CommonSkillLine.Bow, skillName: "Magnum Shot", isUltimate: false, parentSkillName: "Scatter Shot" },
{ id: 214, skillLine: CommonSkillLine.Bow, skillName: "Arrow Spray", isUltimate: false, parentSkillName: null },
{ id: 215, skillLine: CommonSkillLine.Bow, skillName: "Acid Spray", isUltimate: false, parentSkillName: "Arrow Spray" },
{ id: 216, skillLine: CommonSkillLine.Bow, skillName: "Bombard", isUltimate: false, parentSkillName: "Arrow Spray" },
{ id: 217, skillLine: CommonSkillLine.Bow, skillName: "Poison Arrow", isUltimate: false, parentSkillName: null },
{ id: 218, skillLine: CommonSkillLine.Bow, skillName: "Poison Injection", isUltimate: false, parentSkillName: "Poison Arrow" },
{ id: 219, skillLine: CommonSkillLine.Bow, skillName: "Venom Arrow", isUltimate: false, parentSkillName: "Poison Arrow" },

{ id: 225, skillLine: CommonSkillLine.DestructionStaff, skillName: "Elemental Storm", isUltimate: true, parentSkillName: null },
{ id: 226, skillLine: CommonSkillLine.DestructionStaff, skillName: "Elemental Rage", isUltimate: true, parentSkillName: "Elemental Storm" },
{ id: 227, skillLine: CommonSkillLine.DestructionStaff, skillName: "Eye of the Storm", isUltimate: true, parentSkillName: "Elemental Storm" },
{ id: 228, skillLine: CommonSkillLine.DestructionStaff, skillName: "Elemental Explosion", isUltimate: false, parentSkillName: null },
{ id: 229, skillLine: CommonSkillLine.DestructionStaff, skillName: "Force Shock", isUltimate: false, parentSkillName: null },
{ id: 230, skillLine: CommonSkillLine.DestructionStaff, skillName: "Crushing Shock", isUltimate: false, parentSkillName: "Force Shock" },
{ id: 231, skillLine: CommonSkillLine.DestructionStaff, skillName: "Force Pulse", isUltimate: false, parentSkillName: "Force Shock" },
{ id: 232, skillLine: CommonSkillLine.DestructionStaff, skillName: "Wall of Elements", isUltimate: false, parentSkillName: null },
{ id: 233, skillLine: CommonSkillLine.DestructionStaff, skillName: "Elemental Blockade", isUltimate: false, parentSkillName: "Wall of Elements" },
{ id: 234, skillLine: CommonSkillLine.DestructionStaff, skillName: "Unstable Wall of Elements", isUltimate: false, parentSkillName: "Wall of Elements" },
{ id: 235, skillLine: CommonSkillLine.DestructionStaff, skillName: "Destructive Touch", isUltimate: false, parentSkillName: null },
{ id: 236, skillLine: CommonSkillLine.DestructionStaff, skillName: "Destructive Clench", isUltimate: false, parentSkillName: "Destructive Touch" },
{ id: 237, skillLine: CommonSkillLine.DestructionStaff, skillName: "Destructive Reach", isUltimate: false, parentSkillName: "Destructive Touch" },
{ id: 238, skillLine: CommonSkillLine.DestructionStaff, skillName: "Weakness to Elements", isUltimate: false, parentSkillName: null },
{ id: 239, skillLine: CommonSkillLine.DestructionStaff, skillName: "Elemental Drain", isUltimate: false, parentSkillName: "Weakness to Elements" },
{ id: 240, skillLine: CommonSkillLine.DestructionStaff, skillName: "Elemental Susceptibility", isUltimate: false, parentSkillName: "Weakness to Elements" },
{ id: 241, skillLine: CommonSkillLine.DestructionStaff, skillName: "Impulse", isUltimate: false, parentSkillName: null },
{ id: 242, skillLine: CommonSkillLine.DestructionStaff, skillName: "Elemental Ring", isUltimate: false, parentSkillName: "Impulse" },
{ id: 243, skillLine: CommonSkillLine.DestructionStaff, skillName: "Pulsar", isUltimate: false, parentSkillName: "Impulse" },

{ id: 249, skillLine: CommonSkillLine.RestorationStaff, skillName: "Panacea", isUltimate: true, parentSkillName: null },
{ id: 250, skillLine: CommonSkillLine.RestorationStaff, skillName: "Life Giver", isUltimate: true, parentSkillName: "Panacea" },
{ id: 251, skillLine: CommonSkillLine.RestorationStaff, skillName: "Light's Champion", isUltimate: true, parentSkillName: "Panacea" },
{ id: 252, skillLine: CommonSkillLine.RestorationStaff, skillName: "Mender's Bond", isUltimate: false, parentSkillName: null },
{ id: 253, skillLine: CommonSkillLine.RestorationStaff, skillName: "Grand Healing", isUltimate: false, parentSkillName: null },
{ id: 254, skillLine: CommonSkillLine.RestorationStaff, skillName: "Healing Springs", isUltimate: false, parentSkillName: "Grand Healing" },
{ id: 255, skillLine: CommonSkillLine.RestorationStaff, skillName: "Illustrious Healing", isUltimate: false, parentSkillName: "Grand Healing" },
{ id: 256, skillLine: CommonSkillLine.RestorationStaff, skillName: "Regeneration", isUltimate: false, parentSkillName: null },
{ id: 257, skillLine: CommonSkillLine.RestorationStaff, skillName: "Radiating Regeneration", isUltimate: false, parentSkillName: "Regeneration" },
{ id: 258, skillLine: CommonSkillLine.RestorationStaff, skillName: "Rapid Regeneration", isUltimate: false, parentSkillName: "Regeneration" },
{ id: 259, skillLine: CommonSkillLine.RestorationStaff, skillName: "Blessing of Protection", isUltimate: false, parentSkillName: null },
{ id: 260, skillLine: CommonSkillLine.RestorationStaff, skillName: "Blessing of Restoration", isUltimate: false, parentSkillName: "Blessing of Protection" },
{ id: 261, skillLine: CommonSkillLine.RestorationStaff, skillName: "Combat Prayer", isUltimate: false, parentSkillName: "Blessing of Protection" },
{ id: 262, skillLine: CommonSkillLine.RestorationStaff, skillName: "Steadfast Ward", isUltimate: false, parentSkillName: null },
{ id: 263, skillLine: CommonSkillLine.RestorationStaff, skillName: "Healing Ward", isUltimate: false, parentSkillName: "Steadfast Ward" },
{ id: 264, skillLine: CommonSkillLine.RestorationStaff, skillName: "Ward Ally", isUltimate: false, parentSkillName: "Steadfast Ward" },
{ id: 265, skillLine: CommonSkillLine.RestorationStaff, skillName: "Force Siphon", isUltimate: false, parentSkillName: null },
{ id: 266, skillLine: CommonSkillLine.RestorationStaff, skillName: "Quick Siphon", isUltimate: false, parentSkillName: "Force Siphon" },
{ id: 267, skillLine: CommonSkillLine.RestorationStaff, skillName: "Siphon Spirit", isUltimate: false, parentSkillName: "Force Siphon" },

{ id: 273, skillLine: CommonSkillLine.SoulMagic, skillName: "Soul Strike", isUltimate: true, parentSkillName: null },
{ id: 274, skillLine: CommonSkillLine.SoulMagic, skillName: "Shatter Soul", isUltimate: true, parentSkillName: "Soul Strike" },
{ id: 275, skillLine: CommonSkillLine.SoulMagic, skillName: "Soul Assault", isUltimate: true, parentSkillName: "Soul Strike" },
{ id: 276, skillLine: CommonSkillLine.SoulMagic, skillName: "Soul Burst", isUltimate: false, parentSkillName: null },
{ id: 277, skillLine: CommonSkillLine.SoulMagic, skillName: "Wield Soul", isUltimate: false, parentSkillName: null },
{ id: 278, skillLine: CommonSkillLine.SoulMagic, skillName: "Soul Trap", isUltimate: false, parentSkillName: null },
{ id: 279, skillLine: CommonSkillLine.SoulMagic, skillName: "Consuming Trap", isUltimate: false, parentSkillName: "Soul Trap" },
{ id: 280, skillLine: CommonSkillLine.SoulMagic, skillName: "Soul Splitting Trap", isUltimate: false, parentSkillName: "Soul Trap" },

{ id: 284, skillLine: CommonSkillLine.Armor, skillName: "Unstoppable", isUltimate: false, parentSkillName: null },
{ id: 285, skillLine: CommonSkillLine.Armor, skillName: "Immovable", isUltimate: false, parentSkillName: "Unstoppable" },
{ id: 286, skillLine: CommonSkillLine.Armor, skillName: "Unstoppable Brute", isUltimate: false, parentSkillName: "Unstoppable" },
{ id: 294, skillLine: CommonSkillLine.Armor, skillName: "Annulment", isUltimate: false, parentSkillName: null },
{ id: 295, skillLine: CommonSkillLine.Armor, skillName: "Dampen Magic", isUltimate: false, parentSkillName: "Annulment" },
{ id: 296, skillLine: CommonSkillLine.Armor, skillName: "Harness Magicka", isUltimate: false, parentSkillName: "Annulment" },
{ id: 304, skillLine: CommonSkillLine.Armor, skillName: "Evasion", isUltimate: false, parentSkillName: null },
{ id: 305, skillLine: CommonSkillLine.Armor, skillName: "Elude", isUltimate: false, parentSkillName: "Evasion" },
{ id: 306, skillLine: CommonSkillLine.Armor, skillName: "Shuffle", isUltimate: false, parentSkillName: "Evasion" },

{ id: 313, skillLine: CommonSkillLine.Assault, skillName: "War Horn", isUltimate: true, parentSkillName: null },
{ id: 314, skillLine: CommonSkillLine.Assault, skillName: "Aggressive Horn", isUltimate: true, parentSkillName: "War Horn" },
{ id: 315, skillLine: CommonSkillLine.Assault, skillName: "Sturdy Horn", isUltimate: true, parentSkillName: "War Horn" },
{ id: 316, skillLine: CommonSkillLine.Assault, skillName: "Trample", isUltimate: false, parentSkillName: null },
{ id: 317, skillLine: CommonSkillLine.Assault, skillName: "Rapid Maneuver", isUltimate: false, parentSkillName: null },
{ id: 318, skillLine: CommonSkillLine.Assault, skillName: "Charging Maneuver", isUltimate: false, parentSkillName: "Rapid Maneuver" },
{ id: 319, skillLine: CommonSkillLine.Assault, skillName: "Retreating Maneuver", isUltimate: false, parentSkillName: "Rapid Maneuver" },
{ id: 320, skillLine: CommonSkillLine.Assault, skillName: "Vigor", isUltimate: false, parentSkillName: null },
{ id: 321, skillLine: CommonSkillLine.Assault, skillName: "Echoing Vigor", isUltimate: false, parentSkillName: "Vigor" },
{ id: 322, skillLine: CommonSkillLine.Assault, skillName: "Resolving Vigor", isUltimate: false, parentSkillName: "Vigor" },
{ id: 323, skillLine: CommonSkillLine.Assault, skillName: "Caltrops", isUltimate: false, parentSkillName: null },
{ id: 324, skillLine: CommonSkillLine.Assault, skillName: "Anti-Cavalry Caltrops", isUltimate: false, parentSkillName: "Caltrops" },
{ id: 325, skillLine: CommonSkillLine.Assault, skillName: "Razor Caltrops", isUltimate: false, parentSkillName: "Caltrops" },
{ id: 326, skillLine: CommonSkillLine.Assault, skillName: "Magicka Detonation", isUltimate: false, parentSkillName: null },
{ id: 327, skillLine: CommonSkillLine.Assault, skillName: "Inevitable Detonation", isUltimate: false, parentSkillName: "Magicka Detonation" },
{ id: 328, skillLine: CommonSkillLine.Assault, skillName: "Proximity Detonation", isUltimate: false, parentSkillName: "Magicka Detonation" },

{ id: 332, skillLine: CommonSkillLine.Support, skillName: "Barrier", isUltimate: true, parentSkillName: null },
{ id: 333, skillLine: CommonSkillLine.Support, skillName: "Replenishing Barrier", isUltimate: true, parentSkillName: "Barrier" },
{ id: 334, skillLine: CommonSkillLine.Support, skillName: "Reviving Barrier", isUltimate: true, parentSkillName: "Barrier" },
{ id: 335, skillLine: CommonSkillLine.Support, skillName: "Banner Bearer", isUltimate: false, parentSkillName: null },
{ id: 336, skillLine: CommonSkillLine.Support, skillName: "Siege Shield", isUltimate: false, parentSkillName: null },
{ id: 337, skillLine: CommonSkillLine.Support, skillName: "Propelling Shield", isUltimate: false, parentSkillName: "Siege Shield" },
{ id: 338, skillLine: CommonSkillLine.Support, skillName: "Siege Weapon Shield", isUltimate: false, parentSkillName: "Siege Shield" },
{ id: 339, skillLine: CommonSkillLine.Support, skillName: "Purge", isUltimate: false, parentSkillName: null },
{ id: 340, skillLine: CommonSkillLine.Support, skillName: "Cleanse", isUltimate: false, parentSkillName: "Purge" },
{ id: 341, skillLine: CommonSkillLine.Support, skillName: "Efficient Purge", isUltimate: false, parentSkillName: "Purge" },
{ id: 342, skillLine: CommonSkillLine.Support, skillName: "Guard", isUltimate: false, parentSkillName: null },
{ id: 343, skillLine: CommonSkillLine.Support, skillName: "Mystic Guard", isUltimate: false, parentSkillName: "Guard" },
{ id: 344, skillLine: CommonSkillLine.Support, skillName: "Stalwart Guard", isUltimate: false, parentSkillName: "Guard" },
{ id: 345, skillLine: CommonSkillLine.Support, skillName: "Revealing Flare", isUltimate: false, parentSkillName: null },
{ id: 346, skillLine: CommonSkillLine.Support, skillName: "Blinding Flare", isUltimate: false, parentSkillName: "Revealing Flare" },
{ id: 347, skillLine: CommonSkillLine.Support, skillName: "Lingering Flare", isUltimate: false, parentSkillName: "Revealing Flare" },

{ id: 351, skillLine: ClassSkillLine.EarthenHeart, skillName: "Magma Armor", isUltimate: true, parentSkillName: null },
{ id: 352, skillLine: ClassSkillLine.EarthenHeart, skillName: "Corrosive Armor", isUltimate: true, parentSkillName: "Magma Armor" },
{ id: 353, skillLine: ClassSkillLine.EarthenHeart, skillName: "Magma Shell", isUltimate: true, parentSkillName: "Magma Armor" },
{ id: 354, skillLine: ClassSkillLine.EarthenHeart, skillName: "Superheated Ward", isUltimate: false, parentSkillName: null },
{ id: 355, skillLine: ClassSkillLine.EarthenHeart, skillName: "Volcanic Ward", isUltimate: false, parentSkillName: "Superheated Ward" },
{ id: 356, skillLine: ClassSkillLine.EarthenHeart, skillName: "Magma Fist", isUltimate: false, parentSkillName: "Superheated Ward" },
{ id: 357, skillLine: ClassSkillLine.EarthenHeart, skillName: "Molten Weapons", isUltimate: false, parentSkillName: null },
{ id: 358, skillLine: ClassSkillLine.EarthenHeart, skillName: "Igneous Weapons", isUltimate: false, parentSkillName: "Molten Weapons" },
{ id: 359, skillLine: ClassSkillLine.EarthenHeart, skillName: "Molten Armaments", isUltimate: false, parentSkillName: "Molten Weapons" },
{ id: 360, skillLine: ClassSkillLine.EarthenHeart, skillName: "Obsidian Shield", isUltimate: false, parentSkillName: null },
{ id: 361, skillLine: ClassSkillLine.EarthenHeart, skillName: "Fragmented Shield", isUltimate: false, parentSkillName: "Obsidian Shield" },
{ id: 362, skillLine: ClassSkillLine.EarthenHeart, skillName: "Igneous Shield", isUltimate: false, parentSkillName: "Obsidian Shield" },
{ id: 363, skillLine: ClassSkillLine.EarthenHeart, skillName: "Petrify", isUltimate: false, parentSkillName: null },
{ id: 364, skillLine: ClassSkillLine.EarthenHeart, skillName: "Fossilize", isUltimate: false, parentSkillName: "Petrify" },
{ id: 365, skillLine: ClassSkillLine.EarthenHeart, skillName: "Shattering Rocks", isUltimate: false, parentSkillName: "Petrify" },
{ id: 366, skillLine: ClassSkillLine.EarthenHeart, skillName: "Earthspike Mantle", isUltimate: false, parentSkillName: null },
{ id: 367, skillLine: ClassSkillLine.EarthenHeart, skillName: "Earthshield Mantle", isUltimate: false, parentSkillName: "Earthspike Mantle" },
{ id: 368, skillLine: ClassSkillLine.EarthenHeart, skillName: "Shatterspike Mantle", isUltimate: false, parentSkillName: "Earthspike Mantle" },

{ id: 373, skillLine: ClassSkillLine.DraconicPower, skillName: "Dragon Leap", isUltimate: true, parentSkillName: null },
{ id: 374, skillLine: ClassSkillLine.DraconicPower, skillName: "Ferocious Leap", isUltimate: true, parentSkillName: "Dragon Leap" },
{ id: 375, skillLine: ClassSkillLine.DraconicPower, skillName: "Take Flight", isUltimate: true, parentSkillName: "Dragon Leap" },
{ id: 376, skillLine: ClassSkillLine.DraconicPower, skillName: "Dragonfire Breath", isUltimate: false, parentSkillName: null },
{ id: 377, skillLine: ClassSkillLine.DraconicPower, skillName: "Disintegrating Dragonfire", isUltimate: false, parentSkillName: "Dragonfire Breath" },
{ id: 378, skillLine: ClassSkillLine.DraconicPower, skillName: "Engulfing Dragonfire", isUltimate: false, parentSkillName: "Dragonfire Breath" },
{ id: 379, skillLine: ClassSkillLine.DraconicPower, skillName: "Dark Talons", isUltimate: false, parentSkillName: null },
{ id: 380, skillLine: ClassSkillLine.DraconicPower, skillName: "Burning Talons", isUltimate: false, parentSkillName: "Dark Talons" },
{ id: 381, skillLine: ClassSkillLine.DraconicPower, skillName: "Choking Talons", isUltimate: false, parentSkillName: "Dark Talons" },
{ id: 382, skillLine: ClassSkillLine.DraconicPower, skillName: "Dragon Blood", isUltimate: false, parentSkillName: null },
{ id: 383, skillLine: ClassSkillLine.DraconicPower, skillName: "Blood of the Elder Dragon", isUltimate: false, parentSkillName: "Dragon Blood" },
{ id: 384, skillLine: ClassSkillLine.DraconicPower, skillName: "Blood of the Green Dragon", isUltimate: false, parentSkillName: "Dragon Blood" },
{ id: 385, skillLine: ClassSkillLine.DraconicPower, skillName: "Wing Buffet", isUltimate: false, parentSkillName: null },
{ id: 386, skillLine: ClassSkillLine.DraconicPower, skillName: "Fleetstep Wings", isUltimate: false, parentSkillName: "Wing Buffet" },
{ id: 387, skillLine: ClassSkillLine.DraconicPower, skillName: "Protect the Brood", isUltimate: false, parentSkillName: "Wing Buffet" },
{ id: 388, skillLine: ClassSkillLine.DraconicPower, skillName: "Chains of Flame", isUltimate: false, parentSkillName: null },
{ id: 389, skillLine: ClassSkillLine.DraconicPower, skillName: "Chains of Devastation", isUltimate: false, parentSkillName: "Chains of Flame" },
{ id: 390, skillLine: ClassSkillLine.DraconicPower, skillName: "Chains of Dominance", isUltimate: false, parentSkillName: "Chains of Flame" },

{ id: 394, skillLine: ClassSkillLine.ArdentFlame, skillName: "Dragonknight Standard", isUltimate: true, parentSkillName: null },
{ id: 395, skillLine: ClassSkillLine.ArdentFlame, skillName: "Shifting Standard", isUltimate: true, parentSkillName: "Dragonknight Standard" },
{ id: 396, skillLine: ClassSkillLine.ArdentFlame, skillName: "Standard of Might", isUltimate: true, parentSkillName: "Dragonknight Standard" },
{ id: 397, skillLine: ClassSkillLine.ArdentFlame, skillName: "Lava Whip", isUltimate: false, parentSkillName: null },
{ id: 398, skillLine: ClassSkillLine.ArdentFlame, skillName: "Flame Lash", isUltimate: false, parentSkillName: "Lava Whip" },
{ id: 399, skillLine: ClassSkillLine.ArdentFlame, skillName: "Molten Whip", isUltimate: false, parentSkillName: "Lava Whip" },
{ id: 400, skillLine: ClassSkillLine.ArdentFlame, skillName: "Searing Strike", isUltimate: false, parentSkillName: null },
{ id: 401, skillLine: ClassSkillLine.ArdentFlame, skillName: "Burning Embers", isUltimate: false, parentSkillName: "Searing Strike" },
{ id: 402, skillLine: ClassSkillLine.ArdentFlame, skillName: "Searing Claw", isUltimate: false, parentSkillName: "Searing Strike" },
{ id: 403, skillLine: ClassSkillLine.ArdentFlame, skillName: "Core of Flame", isUltimate: false, parentSkillName: null },
{ id: 404, skillLine: ClassSkillLine.ArdentFlame, skillName: "Heart of Flame", isUltimate: false, parentSkillName: "Core of Flame" },
{ id: 405, skillLine: ClassSkillLine.ArdentFlame, skillName: "Soul of Flame", isUltimate: false, parentSkillName: "Core of Flame" },
{ id: 406, skillLine: ClassSkillLine.ArdentFlame, skillName: "Hearthfire", isUltimate: false, parentSkillName: null },
{ id: 407, skillLine: ClassSkillLine.ArdentFlame, skillName: "Fire Keeper", isUltimate: false, parentSkillName: "Hearthfire" },
{ id: 408, skillLine: ClassSkillLine.ArdentFlame, skillName: "Hearth and Home", isUltimate: false, parentSkillName: "Hearthfire" },
{ id: 409, skillLine: ClassSkillLine.ArdentFlame, skillName: "Inferno", isUltimate: false, parentSkillName: null },
{ id: 410, skillLine: ClassSkillLine.ArdentFlame, skillName: "Cauterize", isUltimate: false, parentSkillName: "Inferno" },
{ id: 411, skillLine: ClassSkillLine.ArdentFlame, skillName: "Incinerate", isUltimate: false, parentSkillName: "Inferno" },

{ id: 416, skillLine: ClassSkillLine.AedricSpear, skillName: "Radial Sweep", isUltimate: true, parentSkillName: null },
{ id: 417, skillLine: ClassSkillLine.AedricSpear, skillName: "Crescent Sweep", isUltimate: true, parentSkillName: "Radial Sweep" },
{ id: 418, skillLine: ClassSkillLine.AedricSpear, skillName: "Everlasting Sweep", isUltimate: true, parentSkillName: "Radial Sweep" },
{ id: 419, skillLine: ClassSkillLine.AedricSpear, skillName: "Puncturing Strikes", isUltimate: false, parentSkillName: null },
{ id: 420, skillLine: ClassSkillLine.AedricSpear, skillName: "Biting Jabs", isUltimate: false, parentSkillName: "Puncturing Strikes" },
{ id: 421, skillLine: ClassSkillLine.AedricSpear, skillName: "Puncturing Sweep", isUltimate: false, parentSkillName: "Puncturing Strikes" },
{ id: 422, skillLine: ClassSkillLine.AedricSpear, skillName: "Piercing Javelin", isUltimate: false, parentSkillName: null },
{ id: 423, skillLine: ClassSkillLine.AedricSpear, skillName: "Aurora Javelin", isUltimate: false, parentSkillName: "Piercing Javelin" },
{ id: 424, skillLine: ClassSkillLine.AedricSpear, skillName: "Binding Javelin", isUltimate: false, parentSkillName: "Piercing Javelin" },
{ id: 425, skillLine: ClassSkillLine.AedricSpear, skillName: "Focused Charge", isUltimate: false, parentSkillName: null },
{ id: 426, skillLine: ClassSkillLine.AedricSpear, skillName: "Explosive Charge", isUltimate: false, parentSkillName: "Focused Charge" },
{ id: 427, skillLine: ClassSkillLine.AedricSpear, skillName: "Toppling Charge", isUltimate: false, parentSkillName: "Focused Charge" },
{ id: 428, skillLine: ClassSkillLine.AedricSpear, skillName: "Spear Shards", isUltimate: false, parentSkillName: null },
{ id: 429, skillLine: ClassSkillLine.AedricSpear, skillName: "Blazing Spear", isUltimate: false, parentSkillName: "Spear Shards" },
{ id: 430, skillLine: ClassSkillLine.AedricSpear, skillName: "Luminous Shards", isUltimate: false, parentSkillName: "Spear Shards" },
{ id: 431, skillLine: ClassSkillLine.AedricSpear, skillName: "Sun Shield", isUltimate: false, parentSkillName: null },
{ id: 432, skillLine: ClassSkillLine.AedricSpear, skillName: "Blazing Shield", isUltimate: false, parentSkillName: "Sun Shield" },
{ id: 433, skillLine: ClassSkillLine.AedricSpear, skillName: "Radiant Ward", isUltimate: false, parentSkillName: "Sun Shield" },

{ id: 438, skillLine: ClassSkillLine.DawnsWrath, skillName: "Nova", isUltimate: true, parentSkillName: null },
{ id: 439, skillLine: ClassSkillLine.DawnsWrath, skillName: "Solar Disturbance", isUltimate: true, parentSkillName: "Nova" },
{ id: 440, skillLine: ClassSkillLine.DawnsWrath, skillName: "Solar Prison", isUltimate: true, parentSkillName: "Nova" },
{ id: 441, skillLine: ClassSkillLine.DawnsWrath, skillName: "Sun Fire", isUltimate: false, parentSkillName: null },
{ id: 442, skillLine: ClassSkillLine.DawnsWrath, skillName: "Reflective Light", isUltimate: false, parentSkillName: "Sun Fire" },
{ id: 443, skillLine: ClassSkillLine.DawnsWrath, skillName: "Vampire's Bane", isUltimate: false, parentSkillName: "Sun Fire" },
{ id: 444, skillLine: ClassSkillLine.DawnsWrath, skillName: "Solar Flare", isUltimate: false, parentSkillName: null },
{ id: 445, skillLine: ClassSkillLine.DawnsWrath, skillName: "Dark Flare", isUltimate: false, parentSkillName: "Solar Flare" },
{ id: 446, skillLine: ClassSkillLine.DawnsWrath, skillName: "Solar Barrage", isUltimate: false, parentSkillName: "Solar Flare" },
{ id: 447, skillLine: ClassSkillLine.DawnsWrath, skillName: "Backlash", isUltimate: false, parentSkillName: null },
{ id: 448, skillLine: ClassSkillLine.DawnsWrath, skillName: "Power of the Light", isUltimate: false, parentSkillName: "Backlash" },
{ id: 449, skillLine: ClassSkillLine.DawnsWrath, skillName: "Purifying Light", isUltimate: false, parentSkillName: "Backlash" },
{ id: 450, skillLine: ClassSkillLine.DawnsWrath, skillName: "Eclipse", isUltimate: false, parentSkillName: null },
{ id: 451, skillLine: ClassSkillLine.DawnsWrath, skillName: "Living Dark", isUltimate: false, parentSkillName: "Eclipse" },
{ id: 452, skillLine: ClassSkillLine.DawnsWrath, skillName: "Unstable Core", isUltimate: false, parentSkillName: "Eclipse" },
{ id: 453, skillLine: ClassSkillLine.DawnsWrath, skillName: "Radiant Destruction", isUltimate: false, parentSkillName: null },
{ id: 454, skillLine: ClassSkillLine.DawnsWrath, skillName: "Radiant Glory", isUltimate: false, parentSkillName: "Radiant Destruction" },
{ id: 455, skillLine: ClassSkillLine.DawnsWrath, skillName: "Radiant Oppression", isUltimate: false, parentSkillName: "Radiant Destruction" },

{ id: 460, skillLine: ClassSkillLine.RestoringLight, skillName: "Rite of Passage", isUltimate: true, parentSkillName: null },
{ id: 461, skillLine: ClassSkillLine.RestoringLight, skillName: "Practiced Incantation", isUltimate: true, parentSkillName: "Rite of Passage" },
{ id: 462, skillLine: ClassSkillLine.RestoringLight, skillName: "Remembrance", isUltimate: true, parentSkillName: "Rite of Passage" },
{ id: 463, skillLine: ClassSkillLine.RestoringLight, skillName: "Rushed Ceremony", isUltimate: false, parentSkillName: null },
{ id: 464, skillLine: ClassSkillLine.RestoringLight, skillName: "Breath of Life", isUltimate: false, parentSkillName: "Rushed Ceremony" },
{ id: 465, skillLine: ClassSkillLine.RestoringLight, skillName: "Honor the Dead", isUltimate: false, parentSkillName: "Rushed Ceremony" },
{ id: 466, skillLine: ClassSkillLine.RestoringLight, skillName: "Healing Ritual", isUltimate: false, parentSkillName: null },
{ id: 467, skillLine: ClassSkillLine.RestoringLight, skillName: "Hasty Prayer", isUltimate: false, parentSkillName: "Healing Ritual" },
{ id: 468, skillLine: ClassSkillLine.RestoringLight, skillName: "Ritual of Rebirth", isUltimate: false, parentSkillName: "Healing Ritual" },
{ id: 469, skillLine: ClassSkillLine.RestoringLight, skillName: "Restoring Aura", isUltimate: false, parentSkillName: null },
{ id: 470, skillLine: ClassSkillLine.RestoringLight, skillName: "Radiant Aura", isUltimate: false, parentSkillName: "Restoring Aura" },
{ id: 471, skillLine: ClassSkillLine.RestoringLight, skillName: "Repentance", isUltimate: false, parentSkillName: "Restoring Aura" },
{ id: 472, skillLine: ClassSkillLine.RestoringLight, skillName: "Cleansing Ritual", isUltimate: false, parentSkillName: null },
{ id: 473, skillLine: ClassSkillLine.RestoringLight, skillName: "Extended Ritual", isUltimate: false, parentSkillName: "Cleansing Ritual" },
{ id: 474, skillLine: ClassSkillLine.RestoringLight, skillName: "Ritual of Retribution", isUltimate: false, parentSkillName: "Cleansing Ritual" },
{ id: 475, skillLine: ClassSkillLine.RestoringLight, skillName: "Rune Focus", isUltimate: false, parentSkillName: null },
{ id: 476, skillLine: ClassSkillLine.RestoringLight, skillName: "Channeled Focus", isUltimate: false, parentSkillName: "Rune Focus" },
{ id: 477, skillLine: ClassSkillLine.RestoringLight, skillName: "Restoring Focus", isUltimate: false, parentSkillName: "Rune Focus" },

{ id: 482, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Summon Storm Atronach", isUltimate: true, parentSkillName: null },
{ id: 483, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Greater Storm Atronach", isUltimate: true, parentSkillName: "Summon Storm Atronach" },
{ id: 484, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Summon Charged Atronach", isUltimate: true, parentSkillName: "Summon Storm Atronach" },
{ id: 485, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Summon Unstable Familiar", isUltimate: false, parentSkillName: null },
{ id: 486, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Summon Unstable Clannfear", isUltimate: false, parentSkillName: "Summon Unstable Familiar" },
{ id: 487, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Summon Volatile Familiar", isUltimate: false, parentSkillName: "Summon Unstable Familiar" },
{ id: 488, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Daedric Curse", isUltimate: false, parentSkillName: null },
{ id: 489, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Daedric Prey", isUltimate: false, parentSkillName: "Daedric Curse" },
{ id: 490, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Haunting Curse", isUltimate: false, parentSkillName: "Daedric Curse" },
{ id: 491, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Summon Winged Twilight", isUltimate: false, parentSkillName: null },
{ id: 492, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Summon Twilight Matriarch", isUltimate: false, parentSkillName: "Summon Winged Twilight" },
{ id: 493, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Summon Twilight Tormentor", isUltimate: false, parentSkillName: "Summon Winged Twilight" },
{ id: 494, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Conjured Ward", isUltimate: false, parentSkillName: null },
{ id: 495, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Hardened Ward", isUltimate: false, parentSkillName: "Conjured Ward" },
{ id: 496, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Regenerative Ward", isUltimate: false, parentSkillName: "Conjured Ward" },
{ id: 497, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Bound Armor", isUltimate: false, parentSkillName: null },
{ id: 498, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Bound Aegis", isUltimate: false, parentSkillName: "Bound Armor" },
{ id: 499, skillLine: ClassSkillLine.DaedricSummoning, skillName: "Bound Armaments", isUltimate: false, parentSkillName: "Bound Armor" },

{ id: 504, skillLine: ClassSkillLine.DarkMagic, skillName: "Negate Magic", isUltimate: true, parentSkillName: null },
{ id: 505, skillLine: ClassSkillLine.DarkMagic, skillName: "Absorption Field", isUltimate: true, parentSkillName: "Negate Magic" },
{ id: 506, skillLine: ClassSkillLine.DarkMagic, skillName: "Suppression Field", isUltimate: true, parentSkillName: "Negate Magic" },
{ id: 507, skillLine: ClassSkillLine.DarkMagic, skillName: "Crystal Shard", isUltimate: false, parentSkillName: null },
{ id: 508, skillLine: ClassSkillLine.DarkMagic, skillName: "Crystal Fragments", isUltimate: false, parentSkillName: "Crystal Shard" },
{ id: 509, skillLine: ClassSkillLine.DarkMagic, skillName: "Crystal Weapon", isUltimate: false, parentSkillName: "Crystal Shard" },
{ id: 510, skillLine: ClassSkillLine.DarkMagic, skillName: "Encase", isUltimate: false, parentSkillName: null },
{ id: 511, skillLine: ClassSkillLine.DarkMagic, skillName: "Shattering Spines", isUltimate: false, parentSkillName: "Encase" },
{ id: 512, skillLine: ClassSkillLine.DarkMagic, skillName: "Vibrant Shroud", isUltimate: false, parentSkillName: "Encase" },
{ id: 513, skillLine: ClassSkillLine.DarkMagic, skillName: "Rune Prison", isUltimate: false, parentSkillName: null },
{ id: 514, skillLine: ClassSkillLine.DarkMagic, skillName: "Defensive Rune", isUltimate: false, parentSkillName: "Rune Prison" },
{ id: 515, skillLine: ClassSkillLine.DarkMagic, skillName: "Rune Cage", isUltimate: false, parentSkillName: "Rune Prison" },
{ id: 516, skillLine: ClassSkillLine.DarkMagic, skillName: "Dark Exchange", isUltimate: false, parentSkillName: null },
{ id: 517, skillLine: ClassSkillLine.DarkMagic, skillName: "Dark Conversion", isUltimate: false, parentSkillName: "Dark Exchange" },
{ id: 518, skillLine: ClassSkillLine.DarkMagic, skillName: "Dark Deal", isUltimate: false, parentSkillName: "Dark Exchange" },
{ id: 519, skillLine: ClassSkillLine.DarkMagic, skillName: "Daedric Mines", isUltimate: false, parentSkillName: null },
{ id: 520, skillLine: ClassSkillLine.DarkMagic, skillName: "Daedric Refuge", isUltimate: false, parentSkillName: "Daedric Mines" },
{ id: 521, skillLine: ClassSkillLine.DarkMagic, skillName: "Daedric Tomb", isUltimate: false, parentSkillName: "Daedric Mines" },

{ id: 526, skillLine: ClassSkillLine.StormCalling, skillName: "Overload", isUltimate: true, parentSkillName: null },
{ id: 527, skillLine: ClassSkillLine.StormCalling, skillName: "Energy Overload", isUltimate: true, parentSkillName: "Overload" },
{ id: 528, skillLine: ClassSkillLine.StormCalling, skillName: "Power Overload", isUltimate: true, parentSkillName: "Overload" },
{ id: 529, skillLine: ClassSkillLine.StormCalling, skillName: "Mages' Fury", isUltimate: false, parentSkillName: null },
{ id: 530, skillLine: ClassSkillLine.StormCalling, skillName: "Endless Fury", isUltimate: false, parentSkillName: "Mages' Fury" },
{ id: 531, skillLine: ClassSkillLine.StormCalling, skillName: "Mages' Wrath", isUltimate: false, parentSkillName: "Mages' Fury" },
{ id: 532, skillLine: ClassSkillLine.StormCalling, skillName: "Lightning Form", isUltimate: false, parentSkillName: null },
{ id: 533, skillLine: ClassSkillLine.StormCalling, skillName: "Boundless Storm", isUltimate: false, parentSkillName: "Lightning Form" },
{ id: 534, skillLine: ClassSkillLine.StormCalling, skillName: "Hurricane", isUltimate: false, parentSkillName: "Lightning Form" },
{ id: 535, skillLine: ClassSkillLine.StormCalling, skillName: "Lightning Splash", isUltimate: false, parentSkillName: null },
{ id: 536, skillLine: ClassSkillLine.StormCalling, skillName: "Lightning Flood", isUltimate: false, parentSkillName: "Lightning Splash" },
{ id: 537, skillLine: ClassSkillLine.StormCalling, skillName: "Liquid Lightning", isUltimate: false, parentSkillName: "Lightning Splash" },
{ id: 538, skillLine: ClassSkillLine.StormCalling, skillName: "Surge", isUltimate: false, parentSkillName: null },
{ id: 539, skillLine: ClassSkillLine.StormCalling, skillName: "Critical Surge", isUltimate: false, parentSkillName: "Surge" },
{ id: 540, skillLine: ClassSkillLine.StormCalling, skillName: "Power Surge", isUltimate: false, parentSkillName: "Surge" },
{ id: 541, skillLine: ClassSkillLine.StormCalling, skillName: "Bolt Escape", isUltimate: false, parentSkillName: null },
{ id: 542, skillLine: ClassSkillLine.StormCalling, skillName: "Ball of Lightning", isUltimate: false, parentSkillName: "Bolt Escape" },
{ id: 543, skillLine: ClassSkillLine.StormCalling, skillName: "Streak", isUltimate: false, parentSkillName: "Bolt Escape" },

{ id: 548, skillLine: ClassSkillLine.Assassination, skillName: "Death Stroke", isUltimate: true, parentSkillName: null },
{ id: 549, skillLine: ClassSkillLine.Assassination, skillName: "Incapacitating Strike", isUltimate: true, parentSkillName: "Death Stroke" },
{ id: 550, skillLine: ClassSkillLine.Assassination, skillName: "Soul Harvest", isUltimate: true, parentSkillName: "Death Stroke" },
{ id: 551, skillLine: ClassSkillLine.Assassination, skillName: "Veiled Strike", isUltimate: false, parentSkillName: null },
{ id: 552, skillLine: ClassSkillLine.Assassination, skillName: "Concealed Weapon", isUltimate: false, parentSkillName: "Veiled Strike" },
{ id: 553, skillLine: ClassSkillLine.Assassination, skillName: "Surprise Attack", isUltimate: false, parentSkillName: "Veiled Strike" },
{ id: 554, skillLine: ClassSkillLine.Assassination, skillName: "Teleport Strike", isUltimate: false, parentSkillName: null },
{ id: 555, skillLine: ClassSkillLine.Assassination, skillName: "Ambush", isUltimate: false, parentSkillName: "Teleport Strike" },
{ id: 556, skillLine: ClassSkillLine.Assassination, skillName: "Lotus Fan", isUltimate: false, parentSkillName: "Teleport Strike" },
{ id: 557, skillLine: ClassSkillLine.Assassination, skillName: "Assassin's Blade", isUltimate: false, parentSkillName: null },
{ id: 558, skillLine: ClassSkillLine.Assassination, skillName: "Impale", isUltimate: false, parentSkillName: "Assassin's Blade" },
{ id: 559, skillLine: ClassSkillLine.Assassination, skillName: "Killer's Blade", isUltimate: false, parentSkillName: "Assassin's Blade" },
{ id: 560, skillLine: ClassSkillLine.Assassination, skillName: "Mark Target", isUltimate: false, parentSkillName: null },
{ id: 561, skillLine: ClassSkillLine.Assassination, skillName: "Piercing Mark", isUltimate: false, parentSkillName: "Mark Target" },
{ id: 562, skillLine: ClassSkillLine.Assassination, skillName: "Reaper's Mark", isUltimate: false, parentSkillName: "Mark Target" },
{ id: 563, skillLine: ClassSkillLine.Assassination, skillName: "Grim Focus", isUltimate: false, parentSkillName: null },
{ id: 564, skillLine: ClassSkillLine.Assassination, skillName: "Merciless Resolve", isUltimate: false, parentSkillName: "Grim Focus" },
{ id: 565, skillLine: ClassSkillLine.Assassination, skillName: "Relentless Focus", isUltimate: false, parentSkillName: "Grim Focus" },

{ id: 570, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Consuming Darkness", isUltimate: true, parentSkillName: null },
{ id: 571, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Bolstering Darkness", isUltimate: true, parentSkillName: "Consuming Darkness" },
{ id: 572, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Veil of Blades", isUltimate: true, parentSkillName: "Consuming Darkness" },
{ id: 573, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Shadow Cloak", isUltimate: false, parentSkillName: null },
{ id: 574, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Dark Cloak", isUltimate: false, parentSkillName: "Shadow Cloak" },
{ id: 575, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Shadowy Disguise", isUltimate: false, parentSkillName: "Shadow Cloak" },
{ id: 576, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Path of Darkness", isUltimate: false, parentSkillName: null },
{ id: 577, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Refreshing Path", isUltimate: false, parentSkillName: "Path of Darkness" },
{ id: 578, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Twisting Path", isUltimate: false, parentSkillName: "Path of Darkness" },
{ id: 579, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Blur", isUltimate: false, parentSkillName: null },
{ id: 580, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Mirage", isUltimate: false, parentSkillName: "Blur" },
{ id: 581, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Phantasmal Escape", isUltimate: false, parentSkillName: "Blur" },
{ id: 582, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Aspect of Terror", isUltimate: false, parentSkillName: null },
{ id: 583, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Manifestation of Terror", isUltimate: false, parentSkillName: "Aspect of Terror" },
{ id: 584, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Mass Hysteria", isUltimate: false, parentSkillName: "Aspect of Terror" },
{ id: 585, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Summon Shade", isUltimate: false, parentSkillName: null },
{ id: 586, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Dark Shade", isUltimate: false, parentSkillName: "Summon Shade" },
{ id: 587, skillLine: ClassSkillLine.ShadowyEmbrace, skillName: "Shadow Image", isUltimate: false, parentSkillName: "Summon Shade" },

{ id: 592, skillLine: ClassSkillLine.Siphoning, skillName: "Soul Shred", isUltimate: true, parentSkillName: null },
{ id: 593, skillLine: ClassSkillLine.Siphoning, skillName: "Soul Siphon", isUltimate: true, parentSkillName: "Soul Shred" },
{ id: 594, skillLine: ClassSkillLine.Siphoning, skillName: "Soul Tether", isUltimate: true, parentSkillName: "Soul Shred" },
{ id: 595, skillLine: ClassSkillLine.Siphoning, skillName: "Strife", isUltimate: false, parentSkillName: null },
{ id: 596, skillLine: ClassSkillLine.Siphoning, skillName: "Funnel Health", isUltimate: false, parentSkillName: "Strife" },
{ id: 597, skillLine: ClassSkillLine.Siphoning, skillName: "Swallow Soul", isUltimate: false, parentSkillName: "Strife" },
{ id: 598, skillLine: ClassSkillLine.Siphoning, skillName: "Malevolent Offering", isUltimate: false, parentSkillName: null },
{ id: 599, skillLine: ClassSkillLine.Siphoning, skillName: "Healthy Offering", isUltimate: false, parentSkillName: "Malevolent Offering" },
{ id: 600, skillLine: ClassSkillLine.Siphoning, skillName: "Shrewd Offering", isUltimate: false, parentSkillName: "Malevolent Offering" },
{ id: 601, skillLine: ClassSkillLine.Siphoning, skillName: "Cripple", isUltimate: false, parentSkillName: null },
{ id: 602, skillLine: ClassSkillLine.Siphoning, skillName: "Crippling Grasp", isUltimate: false, parentSkillName: "Cripple" },
{ id: 603, skillLine: ClassSkillLine.Siphoning, skillName: "Debilitate", isUltimate: false, parentSkillName: "Cripple" },
{ id: 604, skillLine: ClassSkillLine.Siphoning, skillName: "Siphoning Strikes", isUltimate: false, parentSkillName: null },
{ id: 605, skillLine: ClassSkillLine.Siphoning, skillName: "Leeching Strikes", isUltimate: false, parentSkillName: "Siphoning Strikes" },
{ id: 606, skillLine: ClassSkillLine.Siphoning, skillName: "Siphoning Attacks", isUltimate: false, parentSkillName: "Siphoning Strikes" },
{ id: 607, skillLine: ClassSkillLine.Siphoning, skillName: "Drain Power", isUltimate: false, parentSkillName: null },
{ id: 608, skillLine: ClassSkillLine.Siphoning, skillName: "Power Extraction", isUltimate: false, parentSkillName: "Drain Power" },
{ id: 609, skillLine: ClassSkillLine.Siphoning, skillName: "Sap Essence", isUltimate: false, parentSkillName: "Drain Power" },

{ id: 614, skillLine: ClassSkillLine.GreenBalance, skillName: "Secluded Grove", isUltimate: true, parentSkillName: null },
{ id: 615, skillLine: ClassSkillLine.GreenBalance, skillName: "Enchanted Forest", isUltimate: true, parentSkillName: "Secluded Grove" },
{ id: 616, skillLine: ClassSkillLine.GreenBalance, skillName: "Healing Thicket", isUltimate: true, parentSkillName: "Secluded Grove" },
{ id: 617, skillLine: ClassSkillLine.GreenBalance, skillName: "Fungal Growth", isUltimate: false, parentSkillName: null },
{ id: 618, skillLine: ClassSkillLine.GreenBalance, skillName: "Enchanted Growth", isUltimate: false, parentSkillName: "Fungal Growth" },
{ id: 619, skillLine: ClassSkillLine.GreenBalance, skillName: "Soothing Spores", isUltimate: false, parentSkillName: "Fungal Growth" },
{ id: 620, skillLine: ClassSkillLine.GreenBalance, skillName: "Healing Seed", isUltimate: false, parentSkillName: null },
{ id: 621, skillLine: ClassSkillLine.GreenBalance, skillName: "Budding Seeds", isUltimate: false, parentSkillName: "Healing Seed" },
{ id: 622, skillLine: ClassSkillLine.GreenBalance, skillName: "Corrupting Pollen", isUltimate: false, parentSkillName: "Healing Seed" },
{ id: 623, skillLine: ClassSkillLine.GreenBalance, skillName: "Living Vines", isUltimate: false, parentSkillName: null },
{ id: 624, skillLine: ClassSkillLine.GreenBalance, skillName: "Leeching Vines", isUltimate: false, parentSkillName: "Living Vines" },
{ id: 625, skillLine: ClassSkillLine.GreenBalance, skillName: "Living Trellis", isUltimate: false, parentSkillName: "Living Vines" },
{ id: 626, skillLine: ClassSkillLine.GreenBalance, skillName: "Lotus Flower", isUltimate: false, parentSkillName: null },
{ id: 627, skillLine: ClassSkillLine.GreenBalance, skillName: "Green Lotus", isUltimate: false, parentSkillName: "Lotus Flower" },
{ id: 628, skillLine: ClassSkillLine.GreenBalance, skillName: "Lotus Blossom", isUltimate: false, parentSkillName: "Lotus Flower" },
{ id: 629, skillLine: ClassSkillLine.GreenBalance, skillName: "Nature's Grasp", isUltimate: false, parentSkillName: null },
{ id: 630, skillLine: ClassSkillLine.GreenBalance, skillName: "Bursting Vines", isUltimate: false, parentSkillName: "Nature's Grasp" },
{ id: 631, skillLine: ClassSkillLine.GreenBalance, skillName: "Nature's Embrace", isUltimate: false, parentSkillName: "Nature's Grasp" },

{ id: 636, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Sleet Storm", isUltimate: true, parentSkillName: null },
{ id: 637, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Northern Storm", isUltimate: true, parentSkillName: "Sleet Storm" },
{ id: 638, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Permafrost", isUltimate: true, parentSkillName: "Sleet Storm" },
{ id: 639, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Frost Cloak", isUltimate: false, parentSkillName: null },
{ id: 640, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Expansive Frost Cloak", isUltimate: false, parentSkillName: "Frost Cloak" },
{ id: 641, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Ice Fortress", isUltimate: false, parentSkillName: "Frost Cloak" },
{ id: 642, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Impaling Shards", isUltimate: false, parentSkillName: null },
{ id: 643, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Gripping Shards", isUltimate: false, parentSkillName: "Impaling Shards" },
{ id: 644, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Winter's Revenge", isUltimate: false, parentSkillName: "Impaling Shards" },
{ id: 645, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Arctic Wind", isUltimate: false, parentSkillName: null },
{ id: 646, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Arctic Blast", isUltimate: false, parentSkillName: "Arctic Wind" },
{ id: 647, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Polar Wind", isUltimate: false, parentSkillName: "Arctic Wind" },
{ id: 648, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Crystallized Shield", isUltimate: false, parentSkillName: null },
{ id: 649, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Crystallized Slab", isUltimate: false, parentSkillName: "Crystallized Shield" },
{ id: 650, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Shimmering Shield", isUltimate: false, parentSkillName: "Crystallized Shield" },
{ id: 651, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Frozen Gate", isUltimate: false, parentSkillName: null },
{ id: 652, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Frozen Device", isUltimate: false, parentSkillName: "Frozen Gate" },
{ id: 653, skillLine: ClassSkillLine.WintersEmbrace, skillName: "Frozen Retreat", isUltimate: false, parentSkillName: "Frozen Gate" },

{ id: 658, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Feral Guardian", isUltimate: true, parentSkillName: null },
{ id: 659, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Eternal Guardian", isUltimate: true, parentSkillName: "Feral Guardian" },
{ id: 660, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Wild Guardian", isUltimate: true, parentSkillName: "Feral Guardian" },
{ id: 661, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Dive", isUltimate: false, parentSkillName: null },
{ id: 662, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Cutting Dive", isUltimate: false, parentSkillName: "Dive" },
{ id: 663, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Screaming Cliff Racer", isUltimate: false, parentSkillName: "Dive" },
{ id: 664, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Scorch", isUltimate: false, parentSkillName: null },
{ id: 665, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Deep Fissure", isUltimate: false, parentSkillName: "Scorch" },
{ id: 666, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Subterranean Assault", isUltimate: false, parentSkillName: "Scorch" },
{ id: 667, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Swarm", isUltimate: false, parentSkillName: null },
{ id: 668, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Fetcher Infection", isUltimate: false, parentSkillName: "Swarm" },
{ id: 669, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Growing Swarm", isUltimate: false, parentSkillName: "Swarm" },
{ id: 670, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Betty Netch", isUltimate: false, parentSkillName: null },
{ id: 671, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Blue Betty", isUltimate: false, parentSkillName: "Betty Netch" },
{ id: 672, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Bull Netch", isUltimate: false, parentSkillName: "Betty Netch" },
{ id: 673, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Falcon's Swiftness", isUltimate: false, parentSkillName: null },
{ id: 674, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Bird of Prey", isUltimate: false, parentSkillName: "Falcon's Swiftness" },
{ id: 675, skillLine: ClassSkillLine.AnimalCompanions, skillName: "Deceptive Predator", isUltimate: false, parentSkillName: "Falcon's Swiftness" },

{ id: 680, skillLine: ClassSkillLine.GraveLord, skillName: "Boneyard", isUltimate: false, parentSkillName: null },
{ id: 681, skillLine: ClassSkillLine.GraveLord, skillName: "Avid Boneyard", isUltimate: false, parentSkillName: "Boneyard" },
{ id: 682, skillLine: ClassSkillLine.GraveLord, skillName: "Unnerving Boneyard", isUltimate: false, parentSkillName: "Boneyard" },
{ id: 683, skillLine: ClassSkillLine.GraveLord, skillName: "Blastbones", isUltimate: false, parentSkillName: null },
{ id: 684, skillLine: ClassSkillLine.GraveLord, skillName: "Stalking Blastbones", isUltimate: false, parentSkillName: "Blastbones" },
{ id: 685, skillLine: ClassSkillLine.GraveLord, skillName: "Blighted Blastbones", isUltimate: false, parentSkillName: "Blastbones" },
{ id: 686, skillLine: ClassSkillLine.GraveLord, skillName: "Skeletal Mage", isUltimate: false, parentSkillName: null },
{ id: 687, skillLine: ClassSkillLine.GraveLord, skillName: "Skeletal Arcanist", isUltimate: false, parentSkillName: "Skeletal Mage" },
{ id: 688, skillLine: ClassSkillLine.GraveLord, skillName: "Skeletal Archer", isUltimate: false, parentSkillName: "Skeletal Mage" },
{ id: 6900, skillLine: ClassSkillLine.GraveLord, skillName: "Shocking Siphon", isUltimate: false, parentSkillName: null },
{ id: 689, skillLine: ClassSkillLine.GraveLord, skillName: "Detonating Siphon", isUltimate: false, parentSkillName: "Shocking Siphon" },
{ id: 690, skillLine: ClassSkillLine.GraveLord, skillName: "Mystic Siphon", isUltimate: false, parentSkillName: "Shocking Siphon" },
{ id: 691, skillLine: ClassSkillLine.GraveLord, skillName: "Pestilent Colossus", isUltimate: true, parentSkillName: null },
{ id: 692, skillLine: ClassSkillLine.GraveLord, skillName: "Glacial Colossus", isUltimate: true, parentSkillName: "Pestilent Colossus" },
{ id: 693, skillLine: ClassSkillLine.GraveLord, skillName: "Frozen Colossus", isUltimate: true, parentSkillName: "Pestilent Colossus" },

{ id: 694, skillLine: ClassSkillLine.LivingDeath, skillName: "Reanimate", isUltimate: true, parentSkillName: null },
{ id: 695, skillLine: ClassSkillLine.LivingDeath, skillName: "Renewing Animation", isUltimate: true, parentSkillName: "Reanimate" },
{ id: 696, skillLine: ClassSkillLine.LivingDeath, skillName: "Animate Blastbones", isUltimate: true, parentSkillName: "Reanimate" },
{ id: 697, skillLine: ClassSkillLine.LivingDeath, skillName: "Render Flesh", isUltimate: false, parentSkillName: null },
{ id: 698, skillLine: ClassSkillLine.LivingDeath, skillName: "Blood Sacrifice", isUltimate: false, parentSkillName: "Render Flesh" },
{ id: 699, skillLine: ClassSkillLine.LivingDeath, skillName: "Resistant Flesh", isUltimate: false, parentSkillName: "Render Flesh" },
{ id: 700, skillLine: ClassSkillLine.LivingDeath, skillName: "Life Amid Death", isUltimate: false, parentSkillName: null },
{ id: 701, skillLine: ClassSkillLine.LivingDeath, skillName: "Life in Death", isUltimate: false, parentSkillName: "Life Amid Death" },
{ id: 702, skillLine: ClassSkillLine.LivingDeath, skillName: "Enduring Undeath", isUltimate: false, parentSkillName: "Life Amid Death" },

{ id: 708, skillLine: ClassSkillLine.BoneTyrant, skillName: "Bone Goliath Transformation", isUltimate: true, parentSkillName: null },
{ id: 709, skillLine: ClassSkillLine.BoneTyrant, skillName: "Bone Goliath", isUltimate: true, parentSkillName: "Bone Goliath Transformation" },
{ id: 710, skillLine: ClassSkillLine.BoneTyrant, skillName: "Pummeling Goliath", isUltimate: true, parentSkillName: "Bone Goliath Transformation" },
{ id: 711, skillLine: ClassSkillLine.BoneTyrant, skillName: "Bone Armor", isUltimate: false, parentSkillName: null },
{ id: 712, skillLine: ClassSkillLine.BoneTyrant, skillName: "Beckoning Armor", isUltimate: false, parentSkillName: "Bone Armor" },
{ id: 713, skillLine: ClassSkillLine.BoneTyrant, skillName: "Summoner's Armor", isUltimate: false, parentSkillName: "Bone Armor" },
{ id: 714, skillLine: ClassSkillLine.BoneTyrant, skillName: "Bone Totem", isUltimate: false, parentSkillName: null },
{ id: 715, skillLine: ClassSkillLine.BoneTyrant, skillName: "Agony Totem", isUltimate: false, parentSkillName: "Bone Totem" },
{ id: 716, skillLine: ClassSkillLine.BoneTyrant, skillName: "Remote Totem", isUltimate: false, parentSkillName: "Bone Totem" },
{ id: 717, skillLine: ClassSkillLine.BoneTyrant, skillName: "Bitter Harvest", isUltimate: false, parentSkillName: null },
{ id: 718, skillLine: ClassSkillLine.BoneTyrant, skillName: "Necrotic Potency", isUltimate: false, parentSkillName: "Bitter Harvest" },
{ id: 7180, skillLine: ClassSkillLine.BoneTyrant, skillName: "Deaden Pain", isUltimate: false, parentSkillName: "Bitter Harvest" },
{ id: 719, skillLine: ClassSkillLine.BoneTyrant, skillName: "Death Scythe", isUltimate: false, parentSkillName: null },
{ id: 720, skillLine: ClassSkillLine.BoneTyrant, skillName: "Hungry Scythe", isUltimate: false, parentSkillName: "Death Scythe" },
{ id: 721, skillLine: ClassSkillLine.BoneTyrant, skillName: "Ruinous Scythe", isUltimate: false, parentSkillName: "Death Scythe" },

{ id: 722, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Remedy Cascade", isUltimate: false, parentSkillName: null },
{ id: 723, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Cascading Fortune", isUltimate: false, parentSkillName: "Remedy Cascade" },
{ id: 724, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Curative Surge", isUltimate: false, parentSkillName: "Remedy Cascade" },
{ id: 725, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Runemend", isUltimate: false, parentSkillName: null },
{ id: 726, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Audacious Runemend", isUltimate: false, parentSkillName: "Runemend" },
{ id: 727, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Evolving Runemend", isUltimate: false, parentSkillName: "Runemend" },
{ id: 728, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Apocryphal Gate", isUltimate: false, parentSkillName: null },
{ id: 729, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Arcanist's Domain", isUltimate: false, parentSkillName: "Apocryphal Gate" },
{ id: 730, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Fleetfooted Gate", isUltimate: false, parentSkillName: "Apocryphal Gate" },
{ id: 731, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Chakram Shields", isUltimate: false, parentSkillName: null },
{ id: 732, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Chakram of Destiny", isUltimate: false, parentSkillName: "Chakram Shields" },
{ id: 733, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Spiteward of the Lucid Mind", isUltimate: false, parentSkillName: "Chakram Shields" },
{ id: 734, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Vitalizing Glyphic", isUltimate: true, parentSkillName: null },
{ id: 735, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Glyphic of the Tides", isUltimate: true, parentSkillName: "Vitalizing Glyphic" },
{ id: 736, skillLine: ClassSkillLine.CurativeRuneforms, skillName: "Resonating Glyphic", isUltimate: true, parentSkillName: "Vitalizing Glyphic" },
{ id: 737, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Abyssal Impact", isUltimate: false, parentSkillName: null },
{ id: 738, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Cephaliarch's Flail", isUltimate: false, parentSkillName: "Abyssal Impact" },
{ id: 739, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "The Imperfect Ring", isUltimate: false, parentSkillName: "Abyssal Impact" },
{ id: 740, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Runic Jolt", isUltimate: false, parentSkillName: null },
{ id: 741, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Runic Sunder", isUltimate: false, parentSkillName: "Runic Jolt" },
{ id: 742, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Runic Embrace", isUltimate: false, parentSkillName: "Runic Jolt" },
{ id: 743, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Fatecarver", isUltimate: false, parentSkillName: null },
{ id: 744, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Exhausting Fatecarver", isUltimate: false, parentSkillName: "Fatecarver" },
{ id: 745, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Escalating Fatecarver", isUltimate: false, parentSkillName: "Fatecarver" },
{ id: 746, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Tome-Bearer's Inspiration", isUltimate: false, parentSkillName: "null" },
{ id: 747, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Inspired Scholarship", isUltimate: false, parentSkillName: "Tome-Bearer's Inspiration" },
{ id: 748, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Recuperative Treatise", isUltimate: false, parentSkillName: "Tome-Bearer's Inspiration" },
{ id: 749, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "The Unblinking Eye", isUltimate: true, parentSkillName: null },
{ id: 750, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "The Languid Eye", isUltimate: true, parentSkillName: "The Unblinking Eye" },
{ id: 751, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "The Tide King's Gaze", isUltimate: true, parentSkillName: "The Unblinking Eye" },
{ id: 752, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Runeblades", isUltimate: false, parentSkillName: null },
{ id: 753, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Escalating Runeblades", isUltimate: false, parentSkillName: "Runeblades" },
{ id: 754, skillLine: ClassSkillLine.HeraldOfTheTomes, skillName: "Writhing Runeblades", isUltimate: false, parentSkillName: "Runeblades" },
{ id: 755, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Fatewoven Armor", isUltimate: false, parentSkillName: null },
{ id: 756, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Cruxweaver Armor", isUltimate: false, parentSkillName: "Fatewoven Armor" },
{ id: 757, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Unbreakable Fate", isUltimate: false, parentSkillName: "Fatewoven Armor" },
{ id: 758, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Runeguard of Freedom", isUltimate: false, parentSkillName: null },
{ id: 759, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Runeguard of Still Waters", isUltimate: false, parentSkillName: "Runeguard of Freedom" },
{ id: 760, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Runeguard of Force", isUltimate: false, parentSkillName: "Runeguard of Freedom" },
{ id: 761, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Gibbering Shield", isUltimate: true, parentSkillName: null },
{ id: 762, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Sanctum of the Abyssal Sea", isUltimate: true, parentSkillName: "Gibbering Shield" },
{ id: 763, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Gibbering Shelter", isUltimate: true, parentSkillName: "Gibbering Shield" },
{ id: 764, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Runic Jolt", isUltimate: false, parentSkillName: null },
{ id: 765, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Runic Embrace", isUltimate: false, parentSkillName: "Runic Jolt" },
{ id: 766, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Runic Sunder", isUltimate: false, parentSkillName: "Runic Jolt" },
{ id: 767, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Runespite Ward", isUltimate: false, parentSkillName: null },
{ id: 768, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Impervious Runeward", isUltimate: false, parentSkillName: "Runespite Ward" },
{ id: 769, skillLine: ClassSkillLine.SoldierOfApocrypha, skillName: "Spite of the Lucid Mind", isUltimate: false, parentSkillName: "Runespite Ward" },
];
